# -*- coding: utf-8 -*-
from docs import *
from photo import scene,fetch
import json
M=lambda i,ph,en,zh:(i,ph,en,zh,"l")
P=lambda k:fetch(json.load(open(f'p{k}A.json'))["url"])
scene("toeic-10-1-a",P("101"),[(600,120,"Contractor","承包商、施工單位",(600,530),26),(1040,120,"Immediate repair","立即維修",(1040,580),22),(300,80,"Plumbing issue","水管問題",(300,300),22),
 (1300,90,"Ceiling fixed","天花板修復",(900,60),22),(1400,900,"Maintenance manager","維護經理",(1400,660),20),(250,900,"Building inspector","建築檢查員",(450,700),22),(900,930,"Routine inspection","例行檢查",(1040,800),22)],
 "Photo: Austin Community College, Flickr (CC BY 2.0)")
scene("toeic-10-2-a",P("102"),[(300,150,"Furnished apartment","附家具的公寓",(760,400),22),(300,500,"Monthly rent ($1,800)","月租金 1,800 美元",(760,650),20),(300,900,"Arrange property viewings","安排實地看房",(300,600),20),
 (1450,900,"Property showcase","房產展示會",(1440,700),20),(1000,930,"Lease starting from March 1st","3 月 1 日開始租約",(1000,860),18),(1400,120,"Listed on website","刊登在網站上",(1240,300),20)],
 "Photo: Kurayba, Flickr (CC BY-SA 2.0)")
scene("toeic-10-3-a",P("103"),[(1000,150,"Meter readings","電表讀數",(600,220),26),(1300,400,"Electricity charges ($3,200)","電費 3,200 美元",(660,330),20),(250,650,"Consumption patterns","用電模式",(500,520),20),
 (500,930,"Regional Power Corporation","區域電力公司",(540,800),20),(1200,930,"Voltage in circuit system stabilized","電路系統電壓已穩定",(860,840),18),(1300,250,"Power outage","停電、斷電",(1300,60),22),(1350,600,"Unusually high","異常偏高",None,22)],
 "Photo: Kai Hendry, Flickr (CC BY 2.0)")
scene("toeic-10-4-a",P("104"),[(1440,200,"Forklift","堆高機",(1440,400),26),(250,150,"At full capacity","完全滿載",(250,400),22),(1000,120,"Capacity of 500 pallets","500 個棧板的總容量",(800,60),20),
 (1200,930,"Loading dock","裝卸碼頭",(1200,800),24),(350,900,"Move pallets to overflow warehouse","將棧板移至溢出倉庫",(500,850),18),(1000,600,"Dispatch","發貨、調度",(1100,650),24),(1450,880,"Freight delivery","貨運配送",(1400,900),20)],
 "Photo: Nick Saltmarsh, Wikimedia Commons (CC BY 2.0)")
make_doc("toeic-10-1-b","email","Mail — Facilities: leak, ceiling and renovation permit",
["A leak in the fourth-floor storage area caused water damage; the building inspector found a plumbing issue.",
"Immediate repair by the contractor takes three days; the third-floor conference room is closed temporarily.",
"The facilities department is replacing the ceiling on the second floor (three weeks) — use alternate routes.",
"A routine inspection raised structural concerns about the foundation on the north side (foundation area).",
"Architect James Morrison of Morrison Construction prepared a blueprint; we will apply for a renovation permit",
"— approval within 5 business days — the west wing project takes four to five weeks and complies with local building codes.",
"The maintenance manager confirms the ceiling fixed in room 401."],
[M(0,"leak in the fourth-floor storage area","Leak in the fourth-floor storage area","四樓儲藏區漏水"),M(0,"water damage","Water damage","水損"),M(0,"building inspector","Building inspector","建築檢查員"),M(0,"plumbing issue","Plumbing issue","水管問題"),
M(1,"Immediate repair","Immediate repair","立即維修"),M(1,"contractor","Contractor","承包商"),M(1,"three days","Three days","3 天工期"),M(1,"third-floor conference room","Third-floor conference room","三樓會議室"),M(1,"closed temporarily","Closed temporarily","暫時封閉"),
M(2,"facilities department","Facilities department","設施管理部門"),M(2,"replacing the ceiling on the second floor","Replacing the ceiling on the second floor","更換二樓天花板"),M(2,"three weeks","Three weeks","3 週工期"),M(2,"alternate routes","Alternate routes","替代路線"),
M(3,"routine inspection","Routine inspection","例行檢查"),M(3,"structural concerns","Structural concerns","結構隱患"),M(3,"foundation on the north side","Foundation on the north side","北側地基"),M(3,"foundation area","Foundation area","地基區域"),
M(4,"Architect James Morrison","Architect James Morrison","建築師詹姆斯·莫里森"),M(4,"Morrison Construction","Morrison Construction","莫里森建設"),M(4,"blueprint","Blueprint","藍圖"),M(4,"apply for a renovation permit","Apply for a renovation permit","申請翻新許可證"),
M(5,"approval within 5 business days","Approval within 5 business days","5 個工作日內獲批"),M(5,"west wing","West wing","西翼大樓"),M(5,"four to five weeks","Four to five weeks","4 至 5 週總工期"),M(5,"complies with local building codes","Complies with local building codes","符合當地建築法規"),
M(6,"maintenance manager","Maintenance manager","維護經理"),M(6,"ceiling fixed","Ceiling fixed","天花板修復"),M(4,"Architect","Architect","建築師")],
subtitle="From: facilities@company.com")
make_doc("toeic-10-2-b","paper","PROPERTY LISTINGS — Riverside Realty",
["Two-bedroom apartment, furnished apartment, 85 square-metres, listed on website today.",
"Monthly rent ($1,800); deposit equal to two months' rent; lease starting from March 1st.",
"Studio apartments and an unfurnished flat available at fair market rent;",
"three-bedroom house ($485,000) — property valuation ($350,000) last year; mortgage options available.",
"Commercial properties: 120 square-metre unfurnished office suite, property valuation ($1,200,000);",
"monthly rent ($3,500) & deposit ($7,000); lease term (March 1st to February 28th); two designated parking spaces.",
"Error correction: the residential lease term runs from April 1st to March 31st. Join our property showcase Saturday",
"— arrange property viewings by phone."],
[M(0,"Two-bedroom apartment","Two-bedroom apartment","兩房公寓"),M(0,"furnished apartment","Furnished apartment","附家具的公寓"),M(0,"85 square-metres","85 square-metres","85 平方公尺"),M(0,"listed on website","Listed on website","刊登在網站上"),
M(1,"Monthly rent ($1,800)","Monthly rent ($1,800)","月租金 1,800 美元"),M(1,"deposit equal to two months' rent","Deposit equal to two months' rent","相當於兩個月租金的押金"),M(1,"lease starting from March 1st","Lease starting from March 1st","3 月 1 日開始租約"),
M(2,"Studio apartments","Studio apartments","開放式套房"),M(2,"unfurnished flat","Unfurnished flat","未附家具的套房"),M(2,"fair market rent","Fair market rent","公平市場租金"),
M(3,"three-bedroom house ($485,000)","Three-bedroom house ($485,000)","485,000 美元的三房獨立屋"),M(3,"property valuation ($350,000)","Property valuation ($350,000)","房產估價 350,000 美元"),M(3,"mortgage options","Mortgage options","房屋貸款選項"),
M(4,"Commercial properties","Commercial properties","商業房產"),M(4,"120 square-metre unfurnished office suite","120 square-metre unfurnished office suite","120 平方公尺無家具辦公套房"),M(4,"property valuation ($1,200,000)","Property valuation ($1,200,000)","房產估價 120 萬美元"),
M(5,"monthly rent ($3,500) & deposit ($7,000)","Monthly rent ($3,500) & Deposit ($7,000)","月租 $3,500、押金 $7,000"),M(5,"lease term (March 1st to February 28th)","Lease term (March 1st to February 28th)","一年商業租約"),M(5,"two designated parking spaces","Two designated parking spaces","兩個指定停車位"),
M(6,"Error correction","Error Correction","筆誤更正考點"),M(6,"lease term runs from April 1st to March 31st","Lease term runs from April 1st to March 31st","租期 4/1 至 3/31"),M(6,"property showcase","Property showcase","房產展示會"),M(7,"arrange property viewings","Arrange property viewings","安排實地看房")],
subtitle="Property listings · residential & commercial")
make_doc("toeic-10-3-b","email","Mail — Electricity charges & elevator inspection",
["Electricity charges ($3,200) this month are unusually high; please check the meter readings.",
"After the power outage we were running the generator continuously (backup generator),",
"which changed our consumption patterns. Utilities are not included in monthly rent, so each tenant",
"must establish their own account with Regional Power Corporation.",
"Building total $48,000 (15% increase): the grid system's voltage in circuit system stabilized after",
"engineers reinforced the circuit connections; infrastructure improvements and energy-efficient options follow.",
"Elevator inspection (April 12th at 2:00 PM, 3 hours duration) — limited elevator service."],
[M(0,"Electricity charges ($3,200)","Electricity charges ($3,200)","電費 3,200 美元"),M(0,"unusually high","Unusually high","異常偏高"),M(0,"meter readings","Meter readings","電表讀數"),
M(1,"power outage","Power outage","停電"),M(1,"running the generator continuously","Running the generator continuously","持續運轉發電機"),M(1,"backup generator","Backup generator","備用發電機"),
M(2,"consumption patterns","Consumption patterns","用電模式"),M(2,"Utilities are not included in monthly rent","Utilities are not included in monthly rent","水電費不含在月租內"),
M(3,"establish their own account","Establish their own account","建立自己的帳戶"),M(3,"Regional Power Corporation","Regional Power Corporation","區域電力公司"),
M(4,"total $48,000 (15% increase)","Total $48,000 (15% increase)","總計 $48,000（上漲 15%）"),M(4,"grid system","Grid system","電力網系統"),M(4,"voltage in circuit system stabilized","Voltage in circuit system stabilized","電路電壓已穩定"),
M(5,"reinforced the circuit connections","Reinforced the circuit connections","加固電路連接"),M(5,"infrastructure improvements","Infrastructure improvements","基礎設施改進"),M(5,"energy-efficient options","Energy-efficient options","節能方案"),
M(6,"Elevator inspection (April 12th at 2:00 PM, 3 hours duration)","Elevator inspection (April 12th at 2:00 PM, 3 hours duration)","4/12 下午 2 點電梯檢查 3 小時"),M(6,"Elevator inspection","Elevator inspection","電梯檢查")],
subtitle="From: building-management@tower.com")
make_doc("toeic-10-4-b","paper","WAREHOUSE OPERATIONS — Storage & dispatch notice",
["Storage unit (20 by 30 feet, climate-control) is at full capacity; move pallets to overflow warehouse.",
"Storage unit (25 by 40 feet) can accommodate units up to 15 feet high; the main storage unit (30 by 50 feet)",
"is positioned near the dispatch area, currently at 80% capacity, up to 20 feet high, capacity of 500 pallets.",
"Freight delivery: trucks arrive by noon at the loading dock — check shipment labels and coordinate with logistics team;",
"every dispatch is recorded in logistics database. Weekdays delivery (6 AM to 8 PM);",
"daily arrival by 10 AM & forklifts ready by 9:30 AM lets us process 20% more shipments per day."],
[M(0,"Storage unit (20 by 30 feet, climate-control)","Storage unit (20 by 30 feet, climate-control)","20×30 英尺溫控儲存單元"),M(0,"at full capacity","At full capacity","完全滿載"),M(0,"move pallets to overflow warehouse","Move pallets to overflow warehouse","將棧板移至溢出倉庫"),
M(1,"Storage unit (25 by 40 feet)","Storage unit (25 by 40 feet)","25×40 英尺儲存單元"),M(1,"accommodate units up to 15 feet high","Accommodate units up to 15 feet high","容納高達 15 英尺"),M(1,"storage unit (30 by 50 feet)","Storage unit (30 by 50 feet)","30×50 英尺主倉庫"),
M(2,"positioned near the dispatch area","Positioned near the dispatch area","定位在發貨區附近"),M(2,"currently at 80% capacity","Currently at 80% capacity","目前 80% 容量"),M(2,"up to 20 feet high","Up to 20 feet high","高達 20 英尺"),M(2,"capacity of 500 pallets","Capacity of 500 pallets","500 個棧板容量"),
M(3,"Freight delivery","Freight delivery","貨運配送"),M(3,"arrive by noon","Arrive by noon","中午前抵達"),M(3,"loading dock","Loading dock","裝卸碼頭"),M(3,"check shipment labels","Check shipment labels","檢查出貨標籤"),M(3,"coordinate with logistics team","Coordinate with logistics team","與物流團隊協調"),
M(4,"dispatch","Dispatch","發貨、調度"),M(4,"recorded in logistics database","Recorded in logistics database","記錄於物流資料庫"),M(4,"Weekdays delivery (6 AM to 8 PM)","Weekdays delivery (6 AM to 8 PM)","平日 6-20 點配送"),
M(5,"daily arrival by 10 AM & forklifts ready by 9:30 AM","Daily arrival by 10 AM & Forklifts ready by 9:30 AM","每日 10 點前到達、9:30 堆高機就緒"),M(5,"process 20% more shipments per day","Process 20% more shipments per day","每天多處理 20%"),M(5,"forklifts","Forklift","堆高機")],
subtitle="Warehouse operations · logistics team")
