# -*- coding: utf-8 -*-
from docs import *
from photo import scene,fetch
import json
M=lambda i,ph,en,zh:(i,ph,en,zh,"l")
P=lambda k:fetch(json.load(open(f'p{k}A.json'))["url"])
scene("toeic-11-3-a",P("113"),[(800,70,"Assembly line","組裝線",None,30),(800,930,"Factory floor","工廠廠房",(800,830),24),(250,150,"Running at full capacity","滿載產能運轉",(240,470),20),
 (1350,150,"Increase the production rate","提高生產速率",(1360,400),20),(1300,900,"Workflow","工作流程",(1200,700),24),(250,900,"Output figures","產出數據",(300,750),22),(800,660,"8,000 units","8,000 件",(720,545),22)],
 "Photo: jurvetson, Flickr (CC BY 2.0)")
scene("toeic-11-4-a",P("114"),[(1200,140,"Protective eyewear","防護眼鏡",(860,265),24),(300,80,"Workplace safety","工作場所安全",(770,110),24),(250,450,"Hazard training","危險培訓",(450,300),22),
 (1350,900,"Official inspection","官方檢查",(1360,600),22),(1300,700,"Permit","許可證",(1360,440),24),(700,930,"Mandatory safety briefing","強制性安全簡報",(600,850),20),(300,930,"Compliance","合規",(400,650),24)],
 "Photo: EU-Ukraine cooperation, Flickr (CC BY-SA 2.0)")
make_doc("toeic-11-1-b","email","Mail — Critical quality control findings",
["The sample batch failed the quality control check: defects affect 20% of our samples;",
"the inspection report shows non-compliance with the specification — a compliance failure.",
"Battery performance issues in 15% of units come from the charging mechanism (supplier's component);",
"approximately 500 units shipped last week may need to be recalled — recall products immediately.",
"Customer feedback is largely positive on camera quality and user interface, but quality concerns remain.",
"The prototype must pass the validation process (validation criteria attached).",
"Review meeting tomorrow; submit your comprehensive review by end of day Friday; final decision next Monday."],
[M(0,"sample batch","Sample batch","樣品批次"),M(0,"failed the quality control check","Failed the quality control check","未通過品質控制檢查"),M(0,"defects affect 20% of our samples","Defects affect 20% of our samples","缺陷影響 20% 樣品"),
M(1,"inspection report","Inspection report","檢驗報告"),M(1,"non-compliance","Non-compliance","不符合"),M(1,"specification","Specification","規格"),M(1,"compliance failure","Compliance failure","合規失敗"),
M(2,"Battery performance issues","Battery performance issues","電池性能問題"),M(2,"15% of units","15% of units","15% 的單位"),M(2,"charging mechanism","Charging mechanism","充電機制"),M(2,"supplier's component","Supplier's component","供應商的零件"),
M(3,"approximately 500 units","Approximately 500 units","約 500 個單位"),M(3,"shipped last week","Shipped last week","上週出貨"),M(3,"recall products","Recall products","召回產品"),M(3,"immediately","Immediately","立即"),
M(4,"Customer feedback","Customer feedback","客戶反饋"),M(4,"largely positive","Largely positive","大多正面"),M(4,"camera quality and user interface","Camera quality and user interface","相機品質與使用者介面"),M(4,"quality concerns","Quality concerns","品質疑慮"),
M(5,"prototype","Prototype","原型"),M(5,"validation process","Validation process","驗證流程"),M(5,"validation criteria","Validation criteria","驗證標準"),
M(6,"Review meeting tomorrow","Tomorrow's meeting","明天的會議"),M(6,"comprehensive review","Comprehensive review","全面審查"),M(6,"by end of day Friday","Submit... by end of day Friday","週五下班前提交"),M(6,"next Monday","Next Monday","下週一"),M(0,"defects","Defects","缺陷"),M(1,"compliance","Compliance","合規")],
subtitle="Critical quality control findings · From: qa-lead@company.com")
make_doc("toeic-11-2-b","email","Mail — Equipment malfunction & procurement upgrade",
["The packaging machine isn't running as fast as it should; the last maintenance check was in March.",
"A malfunction caused eight hours of downtime this week, and a missing part delayed repairs by two weeks.",
"Spare components: inventory is getting low — handle it right away; sourcing a replacement from",
"multiple suppliers rather than single provider will keep procurement streamlined.",
"We will replace the equipment with a state-of-the-art automated system — upgrade next month (October 1st).",
"The upgrade should improve efficiency by 40%; full training is included."],
[M(0,"isn't running as fast as it should","Isn't running as fast as it should","運轉速度不如預期"),M(0,"last maintenance check","Last maintenance check","上次維護檢查"),
M(1,"malfunction","Malfunction","故障"),M(1,"eight hours of downtime this week","Eight hours of downtime this week","本週八小時停機"),M(1,"delayed repairs by two weeks","Delayed repairs by two weeks","維修延遲兩週"),
M(2,"Spare components","Spare components","備用零件"),M(2,"inventory is getting low","Inventory is getting low","庫存不足"),M(2,"handle it right away","Handle it right away","立即處理"),M(2,"sourcing","Sourcing","採購、尋找貨源"),M(2,"replacement","Replacement","替代品"),
M(3,"multiple suppliers rather than single provider","Multiple suppliers rather than single provider","多個供應商而非單一"),M(3,"procurement","Procurement","採購"),M(3,"streamlined","Streamlined","精簡、優化"),
M(4,"replace the equipment","Replace the equipment","更換設備"),M(4,"state-of-the-art","State-of-the-art","最先進的"),M(4,"automated system","Automated system","自動化系統"),M(4,"upgrade next month","Upgrade next month","下個月升級"),M(4,"October 1st","October 1st","10 月 1 日"),
M(5,"improve efficiency by 40%","Improve efficiency by 40%","提升 40% 效率"),M(5,"full training","Full training","完整培訓"),M(1,"downtime","Downtime","停機時間"),M(4,"upgrade","Upgrade","升級")],
subtitle="From: plant-manager@company.com")
make_doc("toeic-11-3-b","email","Mail — Production update: behind schedule",
["Output figures: we are behind by three days on the factory floor — 75% of target (8,000 units).",
"The assembly line is running at full capacity, so to increase the production rate we are adding another shift",
"(add a night shift, 6 PM to 2 AM) to boost capacity and meet the deadline next Friday.",
"Line B is behind by five days: 68% of target (12,000 units) due to assembly delays;",
"arrange extra staff immediately to fulfill orders on time by month-end.",
"Update the workflow and send projected quotas / projections by Friday."],
[M(0,"Output figures","Output figures","產出數據"),M(0,"behind by three days","Behind by three days","落後三天"),M(0,"factory floor","Factory floor","工廠廠房"),M(0,"75% of target","75% of target","目標的 75%"),M(0,"8,000 units","8,000 units","8,000 件"),
M(1,"assembly line","Assembly line","組裝線"),M(1,"running at full capacity","Running at full capacity","滿載產能"),M(1,"increase the production rate","Increase the production rate","提高生產速率"),M(1,"adding another shift","Adding another shift","增加另一個班次"),
M(2,"add a night shift","Add a night shift","增加夜班"),M(2,"6 PM to 2 AM","6 PM to 2 AM","晚上 6 點至凌晨 2 點"),M(2,"boost capacity","Boost capacity","提升產能"),M(2,"meet the deadline next Friday","Meet the deadline next Friday","趕上下週五截止日"),
M(3,"behind by five days","Behind by five days","落後五天"),M(3,"68% of target","68% of target","目標的 68%"),M(3,"12,000 units","12,000 units","12,000 件"),M(3,"assembly delays","Assembly delays","組裝延誤"),
M(4,"arrange extra staff immediately","Arrange... immediately","立即安排"),M(4,"fulfill orders on time","Fulfill orders on time","按時完成訂單"),M(4,"by month-end","By month-end","月底前"),
M(5,"workflow","Workflow","工作流程"),M(5,"projected quotas","Projected quotas","預估配額"),M(5,"projections by Friday","Projections by Friday","週五前的預測報告")],
subtitle="From: production-manager@company.com")
make_doc("toeic-11-4-b","paper","SAFETY NOTICE — Expansion & compliance",
["We are expanding to increase capacity by 30%; workplace safety and compliance are our top priorities.",
"New regulations require a hazard audit and additional certification (updated certification by October 15th);",
"the official inspection is next Monday — the permit depends on it. Brief the team tomorrow.",
"Safety protocol: protective eyewear is mandatory; hazard training (25% of staff still pending) must be",
"completed within six months (by November 20th) — 40% of certification renewals are due then.",
"Mandatory safety briefing: November 10th at 2 PM. Failure to attend means suspension of workplace",
"access privileges. Questions: extension 3344."],
[M(0,"expanding to increase capacity by 30%","Expanding to increase capacity by 30%","擴建增加 30% 產能"),M(0,"workplace safety","Workplace safety","工作場所安全"),M(0,"compliance","Compliance","合規"),M(0,"top priorities","Top priorities","首要任務"),
M(1,"New regulations","New regulations","新法規"),M(1,"hazard audit","Hazard audit","危險稽核"),M(1,"additional certification","Additional certification","額外認證"),M(1,"updated certification","Updated certification","更新的認證"),M(1,"October 15th","October 15th","10 月 15 日"),
M(2,"official inspection","Official inspection","官方檢查"),M(2,"next Monday","Next Monday","下週一"),M(2,"permit","Permit","許可證"),M(2,"Brief the team tomorrow","Brief the team tomorrow","明天向團隊簡報"),
M(3,"Safety protocol","Safety protocol","安全規程"),M(3,"protective eyewear","Protective eyewear","防護眼鏡"),M(3,"hazard training","Hazard training","危險培訓"),M(3,"25%","25%","百分之二十五"),
M(4,"six months","Six months","六個月"),M(4,"November 20th","November 20th","11 月 20 日"),M(4,"40%","40%","百分之四十"),M(4,"certification renewals","Certification renewals","認證更新"),
M(5,"Mandatory safety briefing","Mandatory safety briefing","強制性安全簡報"),M(5,"November 10th at 2 PM","November 10th at 2 PM","11 月 10 日下午 2 點"),M(5,"suspension of workplace","Suspension of workplace access privileges","暫停進入工作場所權限"),M(6,"extension 3344","Extension 3344","分機 3344")],
subtitle="Operations & safety · effective immediately")
make_doc("toeic-11-5-b","slide","Cost Review & Product Launch — Budget Meeting",
["Production costs have increased by 15% (last year: production costs have increased by 20%), so the profit margin fell to 18%.",
"Revised budget: total investment of $5 million; advertising budget remains unchanged at $2 million;",
"promotion budget... $1.5 million, with advertising costs accounting for 60% of the promotion investment.",
"Marketing campaign will highlight efficiency features and sustainability features — review the strategy in three days.",
"Training program... takes two weeks for 50 additional staff; ten days of testing before the official release on Monday.",
"Pre-orders beginning June 1st; shipping July 15th. Next budget review: April 20th at 10 AM."],
[M(0,"Production costs have increased by 15%","Production costs have increased by 15%","生產成本增加 15%"),M(0,"production costs have increased by 20%","Production costs have increased by 20%","生產成本增加 20%"),M(0,"profit margin","Profit margin","利潤率"),M(0,"18%","18%","百分之十八"),
M(1,"Revised budget","Revised budget","修訂預算"),M(1,"total investment of $5 million","Total investment of $5 million","總投資 500 萬美元"),M(1,"advertising budget remains unchanged at $2 million","Advertising budget remains unchanged at $2 million","廣告預算維持 200 萬"),
M(2,"promotion budget... $1.5 million","Promotion budget... $1.5 million","推廣預算 150 萬"),M(2,"advertising costs accounting for 60%","Advertising costs accounting for 60%","廣告費用佔 60%"),M(2,"promotion investment","Promotion investment","推廣投資"),
M(3,"Marketing campaign","Marketing campaign","行銷活動"),M(3,"efficiency features","Efficiency features","效率特色"),M(3,"sustainability features","Sustainability features","永續特色"),M(3,"review the strategy","Review the strategy","審查策略"),M(3,"three days","Three days","三天"),
M(4,"Training program... takes two weeks","Training program... takes two weeks","培訓計畫需兩週"),M(4,"50 additional staff","50 additional staff","50 名額外員工"),M(4,"ten days","Ten days","十天"),M(4,"official release on Monday","Official release on Monday","週一正式發布"),
M(5,"Pre-orders beginning June 1st","Pre-orders beginning June 1st","6 月 1 日開始預購"),M(5,"July 15th","July 15th","7 月 15 日"),M(5,"April 20th at 10 AM","April 20th at 10 AM","4 月 20 日上午 10 點")],
subtitle="Budget management & marketing strategy · Slide 2")
