# -*- coding: utf-8 -*-
from docs import *
from photo import scene,fetch
import json
M=lambda i,ph,en,zh:(i,ph,en,zh,"l")
P=lambda k:fetch(json.load(open(f'p{k}A.json'))["url"])
scene("toeic-12-1-a",P("121"),[(800,70,"Main dining area","主用餐區",None,28),(800,600,"Secure a table","預訂座位",(800,700),24),(800,330,"Private dining section","私人包廂區",(800,450),22),
 (250,500,"Six guests","六位客人",(375,800),22),(1450,930,"Patio seating","露天區座位",(1450,600),22),(250,150,"Intimate ambiance","溫馨的氛圍",(425,375),22),(1400,150,"Establishment","店家、餐館",None,22)],
 "Photo: Basile Morin, Wikimedia Commons (CC BY-SA 4.0)")
scene("toeic-12-2-a",P("122"),[(800,70,"Customizable grain bowl","可客製化穀物碗",None,26),(250,900,"Gluten-free","無麩質的",(300,750),24),(1350,900,"Vegetarian","素食者",(1300,700),24),
 (500,150,"Dairy products","乳製品",(500,250),22),(200,500,"Dressing served separately","醬料分開裝",(150,450),18),(1350,300,"Portion size","份量大小",(1125,300),22),(800,930,"Generous","充足的、豐富的",(825,820),22)],
 "Photo: Prayitno, Flickr (CC BY 2.0)")
scene("toeic-12-3-a",P("123"),[(1025,80,"Same-day delivery","當日送達",(1025,250),26),(300,930,"Takeout","外帶餐點",(625,700),24),(1350,500,"Free delivery","免費外送",(1200,300),24),
 (300,150,"Delivery radius","外送半徑",(375,250),22),(1400,900,"Mobile app","手機應用程式",None,22),(800,930,"Catering services","外燴服務",(800,600),22)],
 "Photo: RG72, Wikimedia Commons (CC BY-SA 4.0)")
scene("toeic-12-4-a",P("124"),[(200,150,"Dinner shift staff","晚班員工",(200,400),22),(750,80,"Hygiene standards","衛生標準",(750,200),24),(1050,150,"Supplier","供應商",(1050,320),24),
 (1400,150,"Urgent staff meeting","緊急員工會議",(1400,560),20),(250,930,"Rotation schedule","輪班表",(575,600),22),(1000,930,"Dishwasher broke down","洗碗機故障了",(900,700),22)],
 "Photo: Fredericknoronha, Wikimedia Commons (CC BY-SA 4.0)")
scene("toeic-12-5-a",P("125"),[(800,70,"Cooking demonstration","烹飪示範",None,28),(1400,120,"Executive chef","行政主廚",(1400,250),24),(1000,930,"Food preparation","食物準備",(1000,550),22),
 (400,930,"Local cuisine","在地料理",(425,300),24),(300,600,"Signature dish","招牌菜",(450,500),24),(1400,930,"Masterclass","大師課",(1250,750),24),(150,150,"Sample","品嚐、試吃",(150,300),24)],
 "Photo: Wikimedia Commons (CC0)")
make_doc("toeic-12-1-b","email","Mail — Reservation for six & catering questionnaire",
["Could you assist me to secure a table for six guests? We prefer a booth with an intimate ambiance;",
"availability during peak hours is limited, so the main dining area or patio seating is fine if you can accommodate us.",
"Reply: Our establishment's earliest availability is 8:30 PM; patrons may join the waiting list in case of a cancellation.",
"Please confirm your reservation — high demand means we reach full capacity by 7 PM.",
"Our private dining section offers an exclusive ambiance; tell us any dietary requirements.",
"Last day for the seasonal wine pairing special — call 555-0142 to pre-select wines."],
[M(0,"assist","Assist","協助"),M(0,"secure a table","Secure a table","預訂座位"),M(0,"six guests","Six guests","六位客人"),M(0,"booth","Booth","雅座、卡座"),M(0,"intimate ambiance","Intimate ambiance","溫馨的氛圍"),
M(1,"availability","Availability","空位狀況"),M(1,"peak hours","Peak hours","尖峰時段"),M(1,"main dining area","Main dining area","主用餐區"),M(1,"patio seating","Patio seating","露天座位"),M(1,"accommodate","Accommodate","容納"),
M(2,"establishment","Establishment","店家"),M(2,"earliest availability","Earliest availability","最早可預訂的空檔"),M(2,"patrons","Patrons","顧客"),M(2,"waiting list","Waiting list","等候名單"),M(2,"cancellation","Cancellation","取消"),
M(3,"confirm your reservation","Confirm your reservation","確認您的預訂"),M(3,"high demand","High demand","高需求"),M(3,"full capacity","Full capacity","客滿"),
M(4,"private dining section","Private dining section","私人包廂區"),M(4,"exclusive ambiance","Exclusive ambiance","專屬高雅氛圍"),M(4,"dietary requirements","Dietary requirements","飲食需求"),
M(5,"Last day","Last day","最後一天"),M(5,"seasonal wine pairing special","Seasonal wine pairing special","季節餐酒搭配特惠"),M(5,"555-0142","555-0142","餐廳電話"),M(5,"pre-select wines","Pre-select wines","預先選酒")],
subtitle="From: elaine@company.com   To: reservations@bistro.com")
make_doc("toeic-12-1-c","paper","CATERING BRIEF — Company banquet, 75 attendees",
["75 attendees with dietary restrictions we must accommodate: 40% vegetarian, with half completely vegan.",
"List all allergens; offer customizable options and build-your-own stations; portion sizes: 1.5 servings per person.",
"Gluten-free options and substitutes for dairy; dressing served separately; nutritional information cards on each table.",
"Plant-based alternatives and meat substitutes for mains; modifications on request; reduced sodium options for the soup."],
[M(0,"75 attendees","75 attendees","75 位參加者"),M(0,"dietary restrictions","Dietary restrictions","飲食限制"),M(0,"accommodate","Accommodate","配合、滿足"),M(0,"40% vegetarian, with half completely vegan","40% vegetarian, with half completely vegan","40% 素食，半數純素"),
M(1,"allergens","Allergens","過敏原"),M(1,"customizable options","Customizable options","可客製化選項"),M(1,"build-your-own","Build-your-own","自選組合"),M(1,"portion sizes","Portion sizes","份量大小"),M(1,"1.5 servings per person","1.5 servings per person","每人 1.5 份"),
M(2,"Gluten-free options","Gluten-free options","無麩質選項"),M(2,"substitutes","Substitutes","替代品"),M(2,"dressing served separately","Dressing served separately","醬料分開供應"),M(2,"nutritional information cards","Nutritional information cards","營養資訊卡"),
M(3,"Plant-based alternatives","Plant-based alternatives","植物性替代品"),M(3,"meat substitutes","Meat substitutes","素肉"),M(3,"modifications","Modifications","修改、調整"),M(3,"reduced sodium options","Reduced sodium options","減鈉選項")],
subtitle="Catering brief · Events team")
make_doc("toeic-12-2-b","paper","MENU NOTES — Ordering & dietary needs",
["Dietary restrictions? Our customizable grain bowl is gluten-free and vegetarian; no dairy products on request.",
"Portion size is generous; dressing served separately; choose one side dish or substitute a salad — modifications at no extra charge.",
"Nutritional information and allergen information (with charts) help guests on a special diet track calories.",
"Notice: due to a shipment delay we are unable to serve shellfish today. Plant-based alternatives are vegan;",
"most dishes are gluten-free upon request. Food allergies? Ask about allergens.",
"Our seasonal menu is launching next week — 15% discount on substitutions and modifications this week."],
[M(0,"Dietary restrictions","Dietary restrictions","飲食限制"),M(0,"customizable grain bowl","Customizable grain bowl","可客製化穀物碗"),M(0,"gluten-free","Gluten-free","無麩質的"),M(0,"vegetarian","Vegetarian","素食者"),M(0,"dairy products","Dairy products","乳製品"),
M(1,"Portion size","Portion size","份量大小"),M(1,"generous","Generous","充足的"),M(1,"dressing served separately","Dressing served separately","醬料分開裝"),M(1,"side dish","Side dish","配菜"),M(1,"substitute","Substitute","替換"),M(1,"modifications","Modifications","調整"),M(1,"no extra charge","No extra charge","不額外收費"),
M(2,"Nutritional information","Nutritional information","營養資訊"),M(2,"allergen information","Allergen information","過敏原資訊"),M(2,"charts","Charts","詳細圖表"),M(2,"special diet","Special diet","特殊飲食"),M(2,"track calories","Track calories","記錄卡路里"),
M(3,"shipment delay","Shipment delay","貨物運輸延誤"),M(3,"unable to serve","Unable to serve","無法供應"),M(3,"shellfish","Shellfish","甲殼類海鮮"),M(3,"Plant-based alternatives","Plant-based alternatives","植物性替代品"),M(3,"vegan","Vegan","純素的"),
M(4,"gluten-free upon request","Gluten-free upon request","依要求做成無麩質"),M(4,"Food allergies","Food allergies","食物過敏"),M(4,"allergens","Allergens","過敏原"),
M(5,"seasonal menu","Seasonal menu","季節性菜單"),M(5,"launching next week","Launching next week","下週推出"),M(5,"15% discount","15% discount","15% 折扣"),M(5,"substitutions","Substitutions","替換")],
subtitle="Green Bowl Café · menu notes")
make_doc("toeic-12-3-b","paper","CATERING & DELIVERY — Promotional offer",
["Catering services for your corporate event: groups of 15 or more get free delivery within our delivery radius.",
"Promotional offer: order before noon for same-day delivery and receive a 20% discount coupon on your next bulk order;",
"we waive the minimum order for members. Loyalty program: double points on the mobile app for takeout.",
"Marketing campaign: no delivery fee with online ordering, 25% off orders over $500 — minimum order requirements don't apply.",
"Customized package deal for 200 attendees: $2,800 total, delivery fee waived, setup service included,",
"plus five discount coupons. Confirm by May 30 · call 555-0199."],
[M(0,"Catering services","Catering services","外燴服務"),M(0,"corporate event","Corporate event","企業活動"),M(0,"groups of 15 or more","Groups of 15 or more","15 人以上團體"),M(0,"free delivery","Free delivery","免費外送"),M(0,"delivery radius","Delivery radius","外送半徑"),
M(1,"Promotional offer","Promotional offer","促銷優惠"),M(1,"before noon","Before noon","中午前"),M(1,"same-day delivery","Same-day delivery","當日送達"),M(1,"20% discount coupon","20% discount coupon","20% 折扣券"),M(1,"bulk order","Bulk order","大量訂購"),
M(2,"waive","Waive","免除"),M(2,"minimum order","Minimum order","最低訂購額"),M(2,"Loyalty program","Loyalty program","忠誠度計畫"),M(2,"double points","Double points","雙倍積分"),M(2,"mobile app","Mobile app","手機應用程式"),M(2,"takeout","Takeout","外帶"),
M(3,"Marketing campaign","Marketing campaign","行銷活動"),M(3,"no delivery fee","No delivery fee","免外送費"),M(3,"online ordering","Online ordering","線上訂餐"),M(3,"25% off","25% off","75 折"),M(3,"over $500","Over $500","超過 500 美元"),M(3,"minimum order requirements don't apply","Minimum order requirements don't apply","最低訂購限制不適用"),
M(4,"Customized package deal","Customized package deal","客製化套餐優惠"),M(4,"200 attendees","200 attendees","200 位參加者"),M(4,"$2,800 total","$2,800 total","總價 2,800 美元"),M(4,"delivery fee waived","Delivery fee waived","免除外送費"),M(4,"setup service","Setup service","現場布置服務"),
M(5,"five discount coupons","Five discount coupons","五張折扣券"),M(5,"Confirm by May 30","Confirm by May 30","5 月 30 日前確認"),M(5,"555-0199","555-0199","廣告專線")],
subtitle="Promotional offer · valid this month")
make_doc("toeic-12-4-b","email","Mail — Urgent staff meeting: dishwasher & operations",
["Urgent staff meeting at 3 PM: the dishwasher broke down and can't be repaired; the maintenance team says the unit",
"needs immediate replacement — the supplier's shipment of the replacement dishwasher arrives Thursday.",
"I adjusted the scheduling: the produce vendor now makes an early morning delivery, and we adjust operational hours —",
"opening at noon instead of 10 AM this week. Dinner shift staff, wear old uniforms until the new ones arrive.",
"Hygiene standards: hygiene certification and food safety compliance training take effect Monday (see training manual);",
"the new rotation schedule, food safety protocols and quality control procedures are attached — please inform my shift.",
"Inventory audit Friday. Mandatory staff meeting next week. Questions: extension 342."],
[M(0,"Urgent staff meeting","Urgent staff meeting","緊急員工會議"),M(0,"dishwasher broke down","Dishwasher broke down","洗碗機故障"),M(0,"can't be repaired","Can't be repaired","無法修理"),M(0,"maintenance team","Maintenance team","維修團隊"),M(0,"unit","Unit","機器"),
M(1,"immediate replacement","Immediate replacement","立即更換"),M(1,"supplier","Supplier","供應商"),M(1,"shipment","Shipment","貨物"),M(1,"replacement dishwasher","Replacement dishwasher","替換用洗碗機"),
M(2,"adjusted the scheduling","Adjusted the scheduling","調整排班"),M(2,"produce vendor","Produce vendor","農產品供應商"),M(2,"early morning delivery","Early morning delivery","清晨送貨"),M(2,"adjust operational hours","Adjust operational hours","調整營業時間"),
M(3,"opening at noon instead of 10 AM","Opening at noon instead of 10 AM","中午開門而非 10 點"),M(3,"Dinner shift staff","Dinner shift staff","晚班員工"),M(3,"wear old uniforms","Wear old uniforms","穿舊制服"),
M(4,"Hygiene standards","Hygiene standards","衛生標準"),M(4,"hygiene certification","Hygiene certification","衛生認證"),M(4,"food safety compliance","Food safety compliance","食品安全合規"),M(4,"take effect","Take effect","生效"),M(4,"training manual","Training manual","訓練手冊"),
M(5,"rotation schedule","Rotation schedule","輪班表"),M(5,"food safety protocols","Food safety protocols","食品安全規程"),M(5,"quality control procedures","Quality control procedures","品質管控程序"),M(5,"inform my shift","Inform my shift","通知我的班次員工"),
M(6,"Inventory audit","Inventory audit","庫存盤點"),M(6,"Mandatory staff meeting","Mandatory staff meeting","強制員工會議"),M(6,"extension 342","Extension 342","分機 342")],
subtitle="From: manager@bistro.com   To: all-staff")
make_doc("toeic-12-5-b","news","RESTAURANT REVIEW — A must-visit destination",
["Food critic James Park writes: the award-winning Maison Bleue exceeds expectations with impeccable service.",
"Antoine Dubois, Executive Chef, brings an innovative fusion approach — combining French techniques with Asian flavors,",
"with ingredients sourced within a 50-mile radius. His signature dish on the seasonal menu earned wide recognition.",
"At the Culinary School, Director Susan Chen hosts a cooking demonstration and masterclass on three signature techniques",
"and food preparation; guests sample local cuisine at the tasting event and receive a complimentary cookbook —",
"his upcoming cookbook is also available for purchase."],
[M(0,"Food critic James Park","Food critic James Park","美食評論家 James Park"),M(0,"award-winning","Award-winning","獲獎的"),M(0,"exceeds expectations","Exceeds expectations","超出預期"),M(0,"impeccable service","Impeccable service","無懈可擊的服務"),
M(1,"Antoine Dubois, Executive Chef","Antoine Dubois, Executive Chef","行政主廚 Antoine Dubois"),M(1,"innovative fusion approach","Innovative fusion approach","創新融合手法"),M(1,"combining French techniques with Asian flavors","Combining French techniques with Asian flavors","法式技巧結合亞洲風味"),
M(2,"sourced within a 50-mile radius","Sourced within a 50-mile radius","採購於方圓 50 英里內"),M(2,"signature dish","Signature dish","招牌菜"),M(2,"seasonal menu","Seasonal menu","季節性菜單"),M(2,"recognition","Recognition","認可、讚譽"),
M(3,"Culinary School","Culinary School","烹飪學校"),M(3,"Director Susan Chen","Director Susan Chen","總監 Susan Chen"),M(3,"cooking demonstration","Cooking demonstration","烹飪示範"),M(3,"masterclass","Masterclass","大師課"),M(3,"three signature techniques","Three signature techniques","三種招牌技術"),
M(4,"food preparation","Food preparation","食物準備"),M(4,"sample","Sample","品嚐"),M(4,"local cuisine","Local cuisine","在地料理"),M(4,"tasting event","Tasting event","品嚐活動"),M(4,"complimentary cookbook","Complimentary cookbook","免費贈送的食譜書"),
M(5,"upcoming cookbook","Upcoming cookbook","即將出版的食譜書"),M(5,"available for purchase","Cookbook available for purchase","食譜書可供購買"),M(0,"Food critic","Food critic","美食評論家")],
subtitle="Restaurant review · City Weekly · must-visit destination")
