# -*- coding: utf-8 -*-
from docs import *
from photo import scene,fetch
import json
M=lambda i,ph,en,zh:(i,ph,en,zh,"l")
P=lambda k:fetch(json.load(open(f'p{k}A.json'))["url"])
scene("toeic-14-1-a",P("141"),[(800,60,"Medical center","醫療中心",None,28),(480,150,"Therapist","治療師",(480,480),24),(1300,150,"Medical history questionnaire","病史問卷",(810,480),20),
 (1090,930,"New patient","新病人、初診病患",(1090,720),22),(1250,320,"Receptionist","接待員",(900,240),22),(1350,900,"Physical therapy evaluation","物理治療評估",(1440,750),18),(250,930,"Check-up","身體檢查",(300,700),24),(250,620,"Paperwork","文書表格",(240,780),22)],
 "Photo: Direct Media, StockSnap (CC0)")
scene("toeic-14-2-a",P("142"),[(300,80,"Pharmacy","藥房、藥局",None,28),(1040,60,"Prescription","處方箋",(1040,150),24),(400,620,"Dosage","劑量",(600,350),24),(1400,600,"Pharmacist","藥劑師",(1360,320),24),
 (1300,900,"Refill","重新調配藥物",(1200,700),24),(800,930,"Allergy medication","過敏藥物",(720,540),22),(200,900,"In stock","有庫存",(300,700),22),(250,300,"Over-the-counter","非處方的（OTC）",(400,300),20)],
 "Photo: U.S. Air Force (public domain)")
scene("toeic-14-5-a",P("145"),[(800,70,"Fitness center","健身中心",None,28),(560,930,"Exercise equipment","運動器材",(560,800),22),(400,130,"Main studio","主教室",(400,240),22),(1300,130,"Membership options","會員選項",None,22),
 (1400,930,"Personal training services","私人訓練教練服務",(1400,600),18),(200,930,"Unlimited use","無限使用",(240,600),22),(960,400,"Wellness program","健康計畫",(960,540),22),(1450,300,"Second floor","二樓",None,22)],
 "Photo: UNE Photos, Flickr (CC BY 2.0)")
make_doc("toeic-14-1-b","email","Mail — Appointments: reschedule & new patient forms",
["Westside Medical Center: we need to reschedule your dental appointment at Greenfield Dental Clinic — the dentist is running behind",
"due to emergency surgery. Openings for tooth cleaning and your whitening appointment: Tuesday works best? Please confirm.",
"New patient: fill in the new patient medical history questionnaire ahead of time; on your first visit, head over to the",
"front desk and arrive 20 minutes before for paperwork. The receptionist can assist you and move your check-up to the same day.",
"Rehabilitation clinic: your physical therapy evaluation with the therapist is upcoming; follow-up visits are available.",
"Cancellations require 48 hours' notice. Bring your patient ID; the dental department is on floor 2."],
[M(0,"Westside Medical Center","Westside Medical Center","西區醫療中心"),M(0,"reschedule","Reschedule","改期"),M(0,"dental appointment","Dental appointment","牙科預約"),M(0,"Greenfield Dental Clinic","Greenfield Dental Clinic","格林菲爾德牙科診所"),M(0,"running behind","Running behind","進度落後"),
M(1,"emergency surgery","Emergency surgery","緊急手術"),M(1,"Openings","Openings","空檔"),M(1,"tooth cleaning","Tooth cleaning","洗牙"),M(1,"whitening appointment","Whitening appointment","美白預約"),M(1,"works best","Works best","最合適"),M(1,"confirm","Confirm","確認"),
M(2,"New patient","New patient","新病人"),M(2,"new patient medical history questionnaire","New patient medical history questionnaire","新病人病史問卷"),M(2,"ahead of time","Ahead of time","提前"),M(2,"first visit","First visit","初診"),M(2,"head over","Head over","前往"),
M(3,"front desk","Front desk","前台"),M(3,"arrive 20 minutes before","Arrive 20 minutes before","提前 20 分鐘到達"),M(3,"paperwork","Paperwork","文書表格"),M(3,"receptionist","Receptionist","接待員"),M(3,"assist","Assist","協助"),M(3,"move","Move","更改時間"),M(3,"check-up","Check-up","身體檢查"),M(3,"same day","Same day","同一天"),
M(4,"Rehabilitation clinic","Rehabilitation clinic","康復診所"),M(4,"physical therapy evaluation","Physical therapy evaluation","物理治療評估"),M(4,"therapist","Therapist","治療師"),M(4,"upcoming","Upcoming","即將到來的"),M(4,"follow-up","Follow-up","後續回診"),M(4,"available","Available","可用的"),
M(5,"48 hours' notice","48 hours' notice","48 小時前通知"),M(5,"patient ID","Patient ID","病歷號碼"),M(5,"dental department","Dental department","牙科部門"),M(0,"Medical Center","Medical center","醫療中心"),M(4,"physical therapy","Physical therapy","物理治療")],
subtitle="From: appointments@westsidemedical.com")
make_doc("toeic-14-2-b","paper","PHARMACY NOTICE — Prescription services",
["Prescription counter: collect your monthly prescription or refill before 8 PM; the pharmacist can verify dosage adjustments.",
"Allergy medication (allergy pills) and seasonal medications are in stock; a specific brand is back in stock — shipment arrives by Thursday.",
"In the meantime, over-the-counter supplements and medical supplies are at discounted prices for valued shoppers; check expiration dates.",
"Order online: prescriptions submitted online 48 hours in advance use our automated ordering process — arrive by Thursday.",
"Helpline: certified pharmacy staff give professional advice on side effects and storage instructions; extended consultations",
"for urgent questions. Insurance coverage verification is required when collecting refills."],
[M(0,"Prescription counter","Prescription counter","配藥櫃台"),M(0,"collect","Collect","領取"),M(0,"monthly prescription","Monthly prescription","每月配藥處方"),M(0,"refill","Refill","補充藥物"),M(0,"before 8 PM","Before 8 PM","晚上 8 點前"),M(0,"pharmacist","Pharmacist","藥劑師"),M(0,"verify","Verify","核對"),M(0,"dosage adjustments","Dosage adjustments","劑量調整"),
M(1,"Allergy medication","Allergy medication","過敏藥物"),M(1,"allergy pills","Allergy pills","過敏藥"),M(1,"seasonal medications","Seasonal medications","季節性藥物"),M(1,"in stock","In stock","有庫存"),M(1,"specific brand","Specific brand","特定品牌"),M(1,"back in stock","Back in stock","重新補足庫存"),M(1,"shipment","Shipment","到貨"),
M(2,"In the meantime","In the meantime","在此期間"),M(2,"over-the-counter","Over-the-counter","非處方的"),M(2,"supplements","Supplements","營養補充品"),M(2,"medical supplies","Medical supplies","醫療用品"),M(2,"discounted prices","Discounted prices","優惠折扣價"),M(2,"valued","Valued","尊貴的"),M(2,"shoppers","Shoppers","顧客"),M(2,"expiration dates","Expiration dates","有效期限"),
M(3,"Order","Order","訂購"),M(3,"submitted online","Submitted online","線上提交"),M(3,"48 hours in advance","48 hours in advance","提前 48 小時"),M(3,"automated ordering process","Automated ordering process","自動化訂購流程"),M(3,"arrive by Thursday","Arrive by Thursday","週四前送達"),
M(4,"Helpline","Helpline","諮詢專線"),M(4,"certified pharmacy staff","Certified pharmacy staff","認證藥劑人員"),M(4,"professional advice","Professional advice","專業建議"),M(4,"side effects","Side effects","副作用"),M(4,"storage instructions","Storage instructions","儲存說明"),M(4,"extended consultations","Extended consultations","延長諮詢門診"),
M(5,"urgent questions","Urgent questions","緊急問題"),M(5,"Insurance coverage verification","Insurance coverage verification","保險給付驗證"),M(5,"collecting refills","Collecting refills","領取補充藥物"),M(0,"Prescription","Prescription","處方箋")],
subtitle="Prescription services · Greenfield Pharmacy")
make_doc("toeic-14-3-b","paper","WELLNESS CENTER — Nutrition consultation",
["At the wellness center, our nutritionist offers personalized nutrition plans and meal plans to improve energy levels.",
"After noting your dietary restrictions, she recommended reducing processed foods and choosing organic options.",
"Learn to read food labels / nutrition facts — calories, protein, fat, sugar — at the wellness education session.",
"Personalized consultations with certified nutrition experts: get your customized plan today."],
[M(0,"nutritionist","Nutritionist","營養師"),M(0,"personalized nutrition plans","Personalized nutrition plans","個人化營養計畫"),M(0,"meal plans","Meal plans","飲食計畫"),M(0,"energy levels","Energy levels","精力水平"),
M(1,"dietary restrictions","Dietary restrictions","飲食限制"),M(1,"recommended reducing","Recommended reducing","建議減少"),M(1,"processed foods","Processed foods","加工食品"),M(1,"organic options","Organic options","有機選擇"),
M(2,"food labels / nutrition facts","Food labels / Nutrition facts","食品標籤／營養成分表"),M(2,"calories, protein, fat, sugar","Calories, protein, fat, sugar","卡路里、蛋白質、脂肪、糖"),M(2,"wellness education session","Wellness education session","健康教育課程"),
M(3,"Personalized consultations","Personalized consultations","個人化諮詢"),M(3,"certified nutrition experts","Certified nutrition experts","認證營養專家"),M(3,"customized plan today","Customized plan today","當天取得客製化計畫"),M(0,"wellness center","Wellness center","健康中心")],
subtitle="Wellness center · nutrition desk")
make_doc("toeic-14-4-b","email","Mail — Billing statement & new electronic health record platform",
["Your billing statement shows a $30 copayment; please verify your policy number and deductible — the claim was approved coverage.",
"A corrected statement will be sent within three business days by the medical office.",
"This weekend we are upgrading to a new electronic health record platform at our newly renovated facility in the hospital complex.",
"The digital system will streamline patient data and medical records, verify approved coverage instantly, and incorporates",
"automated lab results delivery — paper forms are eliminated; results are accessible online through the portal.",
"Before your next visit, sign the consent form at the registration desk. Patient privacy is our top priority."],
[M(0,"billing statement","Billing statement","帳單"),M(0,"copayment","Copayment","部分負擔金額"),M(0,"verify","Verify","核對"),M(0,"policy number","Policy number","保單號碼"),M(0,"deductible","Deductible","自付額"),M(0,"claim","Claim","保險理賠申請"),
M(1,"corrected statement","Corrected statement","修正後帳單"),M(1,"within three business days","Within three business days","三個工作日內"),M(1,"medical office","Medical office","醫療診所"),
M(2,"This weekend","This weekend","本週末"),M(2,"upgrading","Upgrading","升級"),M(2,"electronic health record platform","Electronic health record platform","電子健康記錄平台"),M(2,"newly renovated facility","Newly renovated facility","新翻新設施"),M(2,"hospital complex","Hospital complex","醫院綜合大樓"),
M(3,"digital system","Digital system","數位系統"),M(3,"streamline","Streamline","簡化"),M(3,"patient data","Patient data","病患資料"),M(3,"medical records","Medical records","病歷"),M(3,"approved coverage","Approved coverage","核准保險給付"),M(3,"instantly","Instantly","即時地"),M(3,"incorporates","Incorporates","整合"),
M(4,"automated lab results delivery","Automated lab results delivery","自動化檢驗結果傳送"),M(4,"eliminated","Eliminated","取消的"),M(4,"accessible online","Accessible online","線上可查詢"),M(4,"portal","Portal","入口網站"),
M(5,"Before your next visit","Before your next visit","下次就診前"),M(5,"consent form","Consent form","同意書"),M(5,"registration desk","Registration desk","掛號櫃台"),M(5,"top priority","Top priority","最高優先")],
subtitle="From: billing@westsidemedical.com")
make_doc("toeic-14-5-b","paper","FITNESS CENTER — Corporate membership & wellness program",
["Membership options: unlimited use of exercise equipment, plus yoga, aerobics, strength training — the gym provides everything.",
"Morning yoga class / session at 7:30 in the main studio on the second floor, every Tuesday and Thursday.",
"Our partnership gives comprehensive wellness benefits: corporate membership (use the corporate membership code) with access to",
"personal training services and specialized rehabilitation services (rehabilitation services coverage included).",
"Wellness program launches Monday: 150 minutes of activity weekly to maintain eligibility for health insurance discounts;",
"the wellness coordinator will track your workout attendance and run monthly wellness assessments.",
"Current membership holders get priority booking; we will extend hours to accommodate increased demand. Register at the front desk",
"with the membership application (see the fitness center manager) by month-end. A health fair on June 20th offers a free wellness assessment",
"and a showcase of new equipment; full benefits starting July 1st."],
[M(0,"Membership options","Membership options","會員選項"),M(0,"unlimited use","Unlimited use","無限使用"),M(0,"exercise equipment","Exercise equipment","運動器材"),M(0,"yoga, aerobics, strength training","Yoga, aerobics, strength training","瑜伽、有氧、重訓"),M(0,"gym provides everything","Gym provides everything","健身房提供一切"),
M(1,"Morning yoga class / session","Morning yoga class / session","晨間瑜伽課"),M(1,"7:30 in the main studio on the second floor","7:30 in the main studio on the second floor","7:30 二樓主教室"),M(1,"every Tuesday and Thursday","Every Tuesday and Thursday","每週二與週四"),
M(2,"partnership","Partnership","合作夥伴關係"),M(2,"comprehensive wellness benefits","Comprehensive wellness benefits","全面健康福利"),M(2,"corporate membership","Corporate membership","企業會員"),M(2,"corporate membership code","Corporate membership code","企業會員代碼"),M(2,"access","Access","使用權"),
M(3,"personal training services","Personal training services","私人教練服務"),M(3,"specialized rehabilitation services","Specialized rehabilitation services","專業康復服務"),M(3,"rehabilitation services coverage","Rehabilitation services coverage","復健服務給付"),
M(4,"Wellness program","Wellness program","健康計畫"),M(4,"launches Monday","Launches Monday","週一推出"),M(4,"150 minutes of activity weekly","150 minutes of activity weekly","每週 150 分鐘運動"),M(4,"maintain eligibility","Maintain eligibility","維持資格"),M(4,"health insurance discounts","Health insurance discounts","保費折扣"),
M(5,"wellness coordinator","Wellness coordinator","健康協調員"),M(5,"track your workout attendance","Track your workout attendance","追蹤健身出席率"),M(5,"monthly wellness assessments","Monthly wellness assessments","每月健康評估"),
M(6,"Current membership holders","Current membership holders","現有會員"),M(6,"priority booking","Priority booking","優先預約權"),M(6,"extend hours","Extend hours","延長營業時間"),M(6,"accommodate increased demand","Accommodate increased demand","應對增長需求"),M(6,"Register","Register","登記"),M(6,"front desk","Front desk","前台"),
M(7,"membership application","Membership application","會員申請表"),M(7,"fitness center manager","Fitness center manager","健身中心經理"),M(7,"month-end","Month-end","月底"),M(7,"health fair on June 20th","A health fair on June 20th","6 月 20 日健康博覽會"),M(7,"free wellness assessment","Free wellness assessment","免費健康評估"),
M(8,"showcase","Showcase","展示"),M(8,"full benefits starting July 1st","Full benefits starting July 1st","7 月 1 日福利生效"),M(1,"7:30","7:30","早上 7 點 30 分")],
subtitle="Fitness center · corporate wellness partnership")
