# -*- coding: utf-8 -*-
from docs import *
from photo import scene,fetch
import json
M=lambda i,ph,en,zh:(i,ph,en,zh,"l")
P=lambda k:fetch(json.load(open(f'p{k}A.json'))["url"])
scene("toeic-15-1-a",P("151"),[(800,60,"Branch ATMs","分行提款機",None,28),(400,930,"Withdraw cash","提領現金",(430,700),24),(1200,930,"Deposit check scanning","存款支票掃描",(1150,600),20),
 (1450,700,"3-dollar fee per transaction","每筆交易 3 美元",None,18),(800,500,"Account balance","帳戶餘額",(800,360),22),(250,300,"Deposited","存入（款項）",(400,330),24),(1300,250,"Main branch","總行",None,22)],
 "Photo: Wonderlane, Wikimedia Commons (CC0)")
scene("toeic-15-4-a",P("154"),[(800,70,"Sign the service agreement","簽署服務協議",(1050,490),24),(430,150,"Contract","合約",(450,400),26),(1300,900,"Financial records","財務記錄",(1300,700),22),
 (300,930,"Financial planning","財務規劃",(300,650),22),(1100,930,"Financial consultant","財務顧問",(1050,800),22),(1300,300,"Presentation materials","簡報材料",(1300,240),20),(200,600,"Contract requires your signature","合約需要您的簽名",(400,400),18)],
 "Photo: Homedust, Flickr (CC BY 2.0)")
make_doc("toeic-15-1-b","email","Mail — Loan application approved · Valued Customer",
["Dear Valued Customer: we are pleased to assist you — your loan application has been approved after our review of recent applications.",
"Let me pull up the file: the requested amount at an annual interest rate of 4.5% will be deposited within two business days",
"(the standard is five business days). Please approve the terms to confirm approval; paperwork is at the main branch.",
"Your account is upgraded to the premium tier: waiving all fees to withdraw cash at branch ATMs (no 3-dollar fee per transaction).",
"Questions: extension 2345."],
[M(0,"Valued Customer","Valued Customer","尊榮客戶"),M(0,"assist","Assist","協助"),M(0,"loan application","Loan application","貸款申請"),M(0,"approved","Approved","已批准"),M(0,"review","Review","審查"),M(0,"recent applications","Recent applications","最近的申請案"),
M(1,"pull up","Pull up","調出（資料）"),M(1,"requested amount","Requested amount","申請金額"),M(1,"annual interest rate","Annual interest rate","年利率"),M(1,"deposited","Deposited","存入"),M(1,"two business days","Two business days","兩個工作天"),
M(2,"five business days","Five business days","五個工作天"),M(2,"approve the terms","Approve the terms","同意條款"),M(2,"confirm approval","Confirm approval","確認批准"),M(2,"paperwork","Paperwork","簽約手續"),M(2,"main branch","Main branch","總行"),
M(3,"upgraded","Upgraded","升級的"),M(3,"premium tier","Premium tier","高級會員等級"),M(3,"waiving all fees","Waiving all fees","免除所有手續費"),M(3,"withdraw cash","Withdraw cash","提領現金"),M(3,"branch ATMs","Branch ATMs","分行提款機"),M(3,"3-dollar fee per transaction","3-dollar fee per transaction","每筆交易 3 美元"),
M(4,"extension 2345","Extension 2345","分機 2345")],
subtitle="From: loans@citybank.com")
make_doc("toeic-15-1-c","paper","ONLINE BANKING — Premium tier features",
["Transfer money in real-time with instant confirmation on the mobile application; online banking includes deposit check scanning",
"and investment portfolio tracking. Your monthly statement and investment statements show your account balance.",
"We are enhancing service with an expedited process and extended hours, and reducing the initial deposit — you automatically qualify.",
"Note: no product offers guaranteed returns."],
[M(0,"Transfer money","Transfer money","轉帳"),M(0,"real-time","Real-time","即時的"),M(0,"instant confirmation","Instant confirmation","即時確認"),M(0,"mobile application","Mobile application","手機 App"),M(0,"online banking","Online banking","網路銀行"),M(0,"deposit check scanning","Deposit check scanning","存款支票掃描"),
M(1,"investment portfolio tracking","Investment portfolio tracking","投資組合追蹤"),M(1,"monthly statement","Monthly statement","每月對帳單"),M(1,"investment statements","Investment statements","投資對帳單"),M(1,"account balance","Account balance","帳戶餘額"),
M(2,"enhancing","Enhancing","提升"),M(2,"expedited process","Expedited process","快速流程"),M(2,"extended hours","Extended hours","延長營業時間"),M(2,"reducing","Reducing","調降"),M(2,"initial deposit","Initial deposit","首次存款"),M(2,"automatically qualify","Automatically qualify","自動符合資格"),
M(3,"guaranteed returns","Guaranteed returns","保證回報")],
subtitle="City Bank · premium tier")
make_doc("toeic-15-2-b","email","Mail — Financial review before the budget meeting",
["I have finished reviewing the quarterly revenue: $4.2 million versus our estimate of $3.8 million — 15% above projections,",
"up 18% from last quarter, with positive growth trends; expenses increased by 12%, so the profit margin held at 22%.",
"I still need to check several invoices — invoice processing delays mean some expense reports are not yet processed;",
"I need three more days. The CFO wants revenue projections with increase and decrease scenarios,",
"cost estimates, budget proposals and payment schedules from all department heads on the shared drive by September 30th.",
"Financial review at the budget meeting tomorrow at 10 AM."],
[M(0,"finished reviewing","Finished reviewing","完成審查"),M(0,"quarterly revenue","Quarterly revenue","季度收入"),M(0,"$4.2 million versus our estimate of $3.8 million","$4.2 million versus our estimate of $3.8 million","420 萬 vs 估計 380 萬"),M(0,"15% above projections","15% above projections","高於預估 15%"),
M(1,"up 18% from last quarter","Up 18% from last quarter","比上季成長 18%"),M(1,"positive growth trends","Positive growth trends","正向成長趨勢"),M(1,"expenses increased by 12%","Expenses increased by 12%","支出增加 12%"),M(1,"profit margin","Profit margin","利潤率"),
M(2,"check several invoices","Check several invoices","核對幾張發票"),M(2,"invoice processing delays","Invoice processing delays","發票處理延遲"),M(2,"expense reports","Expense reports","費用報告"),M(2,"processed","Processed","已處理的"),
M(3,"three more days","Three more days","再三天"),M(3,"CFO","CFO","財務長"),M(3,"revenue projections","Revenue projections","營收預測"),M(3,"increase and decrease scenarios","Increase and decrease scenarios","增減情境分析"),
M(4,"cost estimates","Cost estimates","成本估算"),M(4,"budget proposals","Budget proposals","預算提案"),M(4,"payment schedules","Payment schedules","付款時程表"),M(4,"department heads","Department heads","部門主管"),M(4,"shared drive","Shared drive","共享雲端"),M(4,"September 30th","September 30th","9 月 30 日"),
M(5,"Financial review","Financial review","財務審查"),M(5,"budget meeting tomorrow at 10 AM","Budget meeting tomorrow at 10 AM","明天上午 10 點預算會議")],
subtitle="From: finance-analyst@company.com   To: CFO")
make_doc("toeic-15-3-b","paper","BILLING DEPARTMENT — Payment policy update",
["I'd like to inquire about this bill: the total is higher than the original price quoted. Reply: the invoice must include all charges and tax;",
"payment is due by the fifteenth. A ten percent discount applies to orders paid in advance, and we waive the transaction fee for electronic transfer.",
"If you overpay, a refund is processed within seven to ten days after a sale reversal; keep all receipts for sale adjustments at the customer service desk.",
"Effective immediately (starting next Monday): a consistent due date for all clients; customers must pay their bill before receiving service;",
"late payments incur a late charge of 1.5% monthly. We are eliminating fees for automatic deduction and prepaid service packages.",
"Questions: billing department, receipt in hand."],
[M(0,"inquire about this bill","Inquire about this bill","詢問這張帳單"),M(0,"higher than the original price quoted","Higher than the original price quoted","高於原先報價"),M(0,"include all charges and tax","Include all charges and tax","包含所有費用與稅金"),
M(1,"due by the fifteenth","Due by the fifteenth","十五號前到期"),M(1,"ten percent discount","Ten percent discount","九折"),M(1,"orders paid in advance","Orders paid in advance","預付訂單"),M(1,"waive the transaction fee","Waive the transaction fee","免除交易手續費"),M(1,"electronic transfer","Electronic transfer","電子轉帳"),
M(2,"overpay","Overpay","多付款項"),M(2,"refund","Refund","退款"),M(2,"processed within seven to ten days","Processed within seven to ten days","7-10 天內處理"),M(2,"sale reversal","Sale reversal","銷售撤銷"),M(2,"keep all receipts","Keep all receipts","保留所有收據"),M(2,"sale adjustments","Sale adjustments","銷售調整"),M(2,"customer service desk","Customer service desk","客戶服務櫃台"),
M(3,"Effective immediately","Effective immediately","即刻生效"),M(3,"starting next Monday","Starting next Monday","自下週一開始"),M(3,"consistent due date","Consistent due date","統一到期日"),M(3,"pay their bill before receiving service","Pay their bill before receiving service","接受服務前付款"),
M(4,"incur a late charge of 1.5% monthly","Incur a late charge of 1.5% monthly","每月 1.5% 滯納金"),M(4,"eliminating fees","Eliminating fees","取消費用"),M(4,"automatic deduction","Automatic deduction","自動扣款"),M(4,"prepaid service packages","Prepaid service packages","預付服務套餐"),
M(5,"billing department","Billing department","計費部門"),M(5,"receipt","Receipt","收據"),M(1,"discount","Discount","折扣")],
subtitle="Billing department · customer notice")
make_doc("toeic-15-4-b","email","Mail — Upcoming consultation & service agreement",
["Your financial consultant has prepared three different investment options for our upcoming consultation tomorrow at 2 PM at your offices.",
"Please bring relevant documents and records — tax documents and financial records — before the April deadline; you are on track",
"since we filed the necessary records. I scheduled a meeting with the advisor for next Tuesday afternoon; presentation materials are in the secure client portal.",
"To proceed with the proposal, sign the service agreement: the contract requires your signature under our standard service terms —",
"the deadline for signing is just two weeks away. Finalize your service agreement to start financial planning with ongoing support",
"and unlimited client support. Our corporate advisor will review your growth objectives and quarterly projections during the",
"consulting engagement and ensure compliance. Need to reschedule? Reply to this email."],
[M(0,"financial consultant","Financial consultant","財務顧問"),M(0,"three different investment options","Three different investment options","三種投資選擇"),M(0,"upcoming consultation","Upcoming consultation","即將進行的諮詢"),M(0,"tomorrow at 2 PM","Tomorrow at 2 PM","明天下午 2 點"),M(0,"at your offices","At your offices","於您的辦公室"),
M(1,"relevant documents and records","Relevant documents and records","相關文件與記錄"),M(1,"tax documents","Tax documents","稅務文件"),M(1,"financial records","Financial records","財務記錄"),M(1,"before the April deadline","Before the April deadline","四月截止日前"),M(1,"on track","On track","符合進度"),
M(2,"filed the necessary records","Filed the necessary records","歸檔必要記錄"),M(2,"scheduled a meeting with the advisor","Scheduled a meeting with the advisor","安排與顧問會面"),M(2,"next Tuesday afternoon","Next Tuesday afternoon","下週二下午"),M(2,"presentation materials","Presentation materials","簡報材料"),M(2,"secure client portal","Secure client portal","安全客戶入口網站"),
M(3,"proceed with the proposal","Proceed with the proposal","繼續進行提案"),M(3,"sign the service agreement","Sign the service agreement","簽署服務協議"),M(3,"contract requires your signature","Contract requires your signature","合約需要您的簽名"),M(3,"standard service terms","Standard service terms","標準服務條款"),
M(4,"deadline for signing","Deadline for signing","簽約截止日期"),M(4,"just two weeks away","Just two weeks away","僅剩兩週"),M(4,"Finalize your service agreement","Finalize your service agreement","定案服務協議"),M(4,"financial planning","Financial planning","財務規劃"),M(4,"ongoing support","Ongoing support","持續支援"),
M(5,"unlimited client support","Unlimited client support","無限客戶支援"),M(5,"corporate advisor","Corporate advisor","企業顧問"),M(5,"growth objectives","Growth objectives","增長目標"),M(5,"quarterly projections","Quarterly projections","季度預測"),
M(6,"consulting engagement","Consulting engagement","諮詢業務"),M(6,"ensure compliance","Ensure compliance","確保合規"),M(6,"reschedule","Reschedule","改期"),M(3,"contract","Contract","合約")],
subtitle="From: advisor@finplan.com")
