# -*- coding: utf-8 -*-
from docs import *
make_doc("toeic-5-1-b","news","Business Daily · Conglomerates announce joint venture",
["Two of Asia's largest conglomerates announced a joint venture today,",
"combining their expertise and resources to build a regional distribution network.",
"Analysts predict the deal could nearly double their combined market share",
"and lift market value by 15%. The joint venture agreement was finalized",
"on Monday and is pending regulatory approval; operations are expected to begin",
"in Q3. The cooperation follows a wave of merger and acquisition activity",
"as firms pursue emerging markets and strong prospects for future growth."],
[(0,"conglomerates","Conglomerates","企業集團","l"),(0,"joint venture","Joint venture","合資企業","l"),
(1,"combining their expertise and resources","Combining their expertise and resources","結合他們的專業與資源","l"),(1,"distribution network","Distribution network","經銷網絡","l"),
(2,"Analysts predict","Analysts predict","分析師預測","l"),(2,"nearly double","Nearly double","幾乎翻倍","l"),(2,"market share","Market share","市占率","l"),
(3,"market value","Market value","市值","l"),(3,"joint venture agreement","Joint venture agreement","合資協議","l"),(3,"finalized","Finalized","定案、完成","l"),
(4,"pending regulatory approval","Pending regulatory approval","待法規核准","l"),(4,"operations","Operations","營運","l"),(4,"expected to begin","Expected to begin","預計開始","l"),
(5,"cooperation","Cooperation","合作","l"),(5,"merger and acquisition","Merger and acquisition","併購（M&A）","l"),
(6,"pursue","Pursue","追求","l"),(6,"emerging markets","Emerging markets","新興市場","l"),(6,"strong prospects for future growth","Strong prospects for future growth","強勁的未來成長前景","l")],
subtitle="Tuesday, September 17 · Markets")
make_doc("toeic-5-1-c","slide","Strategic Planning 2027 — Market Entry Plan",
["Proposal: expand into the Southeast Asian market (business expansion).",
"Management feels our competitive positioning is quite different from that of our competitors.",
"Diversification: add three new product lines to capture emerging demand.",
"Implementation phase starts in Q2 — project is on track.",
"Corporate growth target: +25% revenue; diversify revenue sources."],
[(0,"Proposal","Proposal","提案","l"),(0,"expand into","Expand into","擴張進入（市場）","l"),(0,"Southeast Asian market","Southeast Asian market","東南亞市場","l"),(0,"business expansion","Business expansion","業務擴張","l"),
(1,"Management feels","Management feels","管理層認為","l"),(1,"competitive positioning","Competitive positioning","競爭定位","l"),(1,"quite different from that of our competitors","Quite different from that of our competitors","與競爭者大不相同","l"),
(2,"Diversification","Diversification","多元化","l"),(2,"product lines","Product lines","產品線","l"),(2,"capture","Capture","把握、奪取（機會、市場）","l"),
(3,"Implementation phase","Implementation phase","執行階段","l"),(3,"on track","On track","按計畫進行、進度正常","l"),
(4,"Corporate growth","Corporate growth","企業成長","l"),(4,"diversify","Diversify","使多元化","l")],
subtitle="Strategic planning · Market entry plan · Slide 3 of 12",size=18,gap=60,
extra=R(180,480,1240,140,"#eff6ff",rx=10)+T(800,530,"Strategic planning  →  Market entry plan  →  Implementation",20,"#1e3a5f")+T(800,570,"SE Asia  ·  3 product lines  ·  Q2 kickoff  ·  +25% growth",16,"#475569"))
make_doc("toeic-5-1-d","memo","To: All staff  ·  From: CEO",
["Subject: AI & Robotics Initiative",
"Our innovation team is transforming traditional operations with artificial intelligence",
"and robotics. This ambitious initiative is targeting emerging trends in automation.",
"Research designs and implementation guidelines will reshape how we work.",
"Management has made a firm commitment: the first phase is expected to begin in March.",
"Industry leaders will share best practices at our annual convention and conference."],
[(0,"Initiative","Initiative","倡議、計畫","l"),
(1,"innovation team","Innovation team","創新團隊","l"),(1,"transforming","Transforming","轉型","l"),(1,"traditional","Traditional","傳統的","l"),(1,"artificial intelligence","Artificial intelligence","人工智慧","l"),
(2,"robotics","Robotics","機器人學","l"),(2,"ambitious","Ambitious","雄心勃勃的","l"),(2,"targeting","Targeting","以…為目標","l"),(2,"emerging trends","Emerging trends","新興趨勢","l"),
(3,"Research designs","Research designs","研究設計","l"),(3,"implementation guidelines","Implementation guidelines","實施指南","l"),(3,"reshape","Reshape","重塑","l"),
(4,"commitment","Commitment","承諾","l"),
(5,"Industry leaders","Industry leaders","產業領袖","l"),(5,"best practices","Best practices","最佳實務","l"),(5,"convention","Convention","大會","l"),(5,"conference","Conference","研討會","l")],
subtitle="Date: September 17  ·  Re: Strategic initiative")
