# -*- coding: utf-8 -*-
from docs import *
M=lambda i,ph,en,zh:(i,ph,en,zh,"l")
# ===== 5-2 =====
make_doc("toeic-5-2-b","paper","MARKET RESEARCH REPORT — Consumer Behavior 2026",
["Market research summary — key findings:","Research has shown that our target audience (ages 25–40, metropolitan areas)",
"prefers eco-friendly products and values sustainable products.",
"Key insight: consumer behavior in these demographics is crucial to growth potential.",
"Specifically, 68% of respondents identified price as the primary factor;",
"results indicate that convenience is primarily a concern in cities.",
"Full data available at the front desk."],
[M(1,"Research has shown","Research has shown","研究已顯示"),M(1,"target audience","Target audience","目標受眾"),M(1,"metropolitan areas","Metropolitan areas","都會區"),
M(2,"prefers","Prefers","偏好"),M(2,"eco-friendly products","Eco-friendly products","環保產品"),M(2,"values","Values","重視"),M(2,"sustainable products","Sustainable products","永續產品"),
M(3,"insight","Insight","洞察、見解"),M(3,"consumer behavior","Consumer behavior","消費者行為"),M(3,"demographics","Demographics","人口統計族群"),M(3,"crucial","Crucial","至關重要的"),M(3,"growth potential","Growth potential","成長潛力"),
M(4,"Specifically","Specifically","特別地"),M(4,"identified","Identified","找出、確認"),M(5,"indicate","Indicate","顯示"),M(5,"primarily","Primarily","主要地"),
M(6,"available","Available","可取得的"),M(6,"front desk","Front desk","櫃檯"),M(0,"Market research","Market research","市場研究")],
subtitle="Prepared by the Marketing Analytics Team · Market research summary")
make_doc("toeic-5-2-c","email","Mail — Marketing strategy: product launch",
["Team leaders, please review the attached marketing strategy.",
"We will adjust the advertising campaign to focus on social media",
"and interactive content — digital channels are well suited to our",
"target group. This should boost brand loyalty and customer satisfaction,",
"and strengthen our competitive advantage. Sales projections are attached.",
"The product launch is scheduled for May 5. We will target only",
"metropolitan customers in the first phase."],
[M(0,"Team leaders","Team leaders","團隊主管"),M(0,"review","Review","審閱"),M(0,"attached","Attached","附上的"),M(0,"marketing strategy","Marketing strategy","行銷策略"),
M(1,"adjust","Adjust","調整"),M(1,"advertising campaign","Advertising campaign","廣告活動"),M(1,"focus on","Focus on","聚焦於"),M(1,"social media","Social media","社群媒體"),
M(2,"interactive content","Interactive content","互動式內容"),M(2,"digital","Digital","數位的"),M(2,"well suited to","Well suited to","適合"),
M(3,"boost","Boost","提升"),M(3,"brand loyalty","Brand loyalty","品牌忠誠度"),M(3,"customer satisfaction","Customer satisfaction","顧客滿意度"),
M(4,"strengthen","Strengthen","強化"),M(4,"competitive advantage","Competitive advantage","競爭優勢"),M(4,"Sales projections","Sales projections","銷售預測"),
M(5,"product launch","Product launch","產品發表"),M(5,"scheduled for","Scheduled for","預定於"),M(5,"target","Target","鎖定、以…為目標"),M(5,"only","Only","僅、只")],
subtitle="From: marketing-director@company.com   To: team-leaders")
# ===== 5-3 =====
make_doc("toeic-5-3-b","paper","SERVICE AGREEMENT — Contract Terms (excerpt)",
["1. This service agreement is a comprehensive legal agreement; its contract terms and provisions are clearly defined.",
"2. Warranty coverage: standard warranties cover manufacturing defects for 12 months;",
"   an extended warranty may be purchased prior to product delivery.",
"3. Service commencement: services begin on the effective date stated above.",
"4. Disputes shall be settled in the jurisdictions of Taipei, Taiwan.",
"5. Contract templates are provided by the Legal Department; requests for",
"   clarification must be submitted explicitly in writing."],
[M(0,"legal agreement","Legal agreement","法律協議"),M(0,"comprehensive","Comprehensive","完整的、全面的"),M(0,"provisions","Provisions","（合約）條款"),M(0,"clearly defined","Clearly defined","明確定義的"),
M(1,"Warranty coverage","Warranty coverage","保固範圍"),M(1,"standard warranties","Standard warranties","標準保固"),M(1,"manufacturing defects","Manufacturing defects","製造瑕疵"),
M(2,"extended warranty","Extended warranty","延長保固"),M(2,"prior to","Prior to","在…之前"),M(2,"product delivery","Product delivery","產品交付"),
M(3,"Service commencement","Service commencement","服務開始"),M(3,"effective date","Effective date","生效日期"),
M(4,"Disputes","Disputes","爭議"),M(4,"jurisdictions","Jurisdictions","司法管轄區"),
M(5,"Contract templates","Contract templates","合約範本"),M(5,"Legal Department","Legal Department","法務部"),M(6,"clarification","Clarification","釐清"),M(6,"explicitly","Explicitly","明確地"),M(0,"contract terms","Contract terms","合約條款"),M(0,"service agreement","Service agreement","服務協議")],
subtitle="Between Wesley Supply Co. (Provider) and ABC Corp. (Client)  ·  Service agreement No. SA-2026-114")
make_doc("toeic-5-3-c","email","Mail — Amendment to service agreement",
["We wish to amend Section 2 of the service agreement to align with new regulations.",
"The modifications are listed in the attached amendment; all other terms remain unchanged.",
"Please sign and return the acknowledgment form within 10 days.",
"Vendor management policies now require stricter compliance requirements:",
"only approved vendors with valid certification status and complete documentation",
"may receive purchase orders through the procurement process.",
"Submit requests for exceptions in advance; late requests will not be considered.",
"Standard warranties are no longer sufficient for medical-grade shipments."],
[M(0,"amend","Amend","修改（合約）"),M(0,"align with","Align with","與…一致"),M(0,"regulations","Regulations","法規"),
M(1,"modifications","Modifications","修改內容"),M(1,"amendment","Amendment","修訂（案）"),M(1,"remain unchanged","Remain unchanged","保持不變"),
M(2,"sign and return","Sign and return","簽署並交回"),M(2,"acknowledgment form","Acknowledgment form","確認書"),
M(3,"Vendor management policies","Vendor management policies","供應商管理政策"),M(3,"stricter","Stricter","更嚴格的"),M(3,"compliance requirements","Compliance requirements","合規要求"),
M(4,"approved vendors","Approved vendors","核准的供應商"),M(4,"certification status","Certification status","認證狀態"),M(4,"documentation","Documentation","文件"),
M(5,"purchase orders","Purchase orders","採購訂單"),M(5,"procurement process","Procurement process","採購流程"),
M(6,"Submit requests","Submit requests","提出申請"),M(6,"in advance","In advance","提前"),M(6,"will not be considered","Will not be considered","將不予考慮"),
M(7,"no longer sufficient","No longer sufficient","不再足夠"),M(7,"shipments","Shipments","貨物、出貨")],
subtitle="From: legal@wesleysupply.com   To: all suppliers")
make_doc("toeic-5-3-d","memo","Vendor management  ·  Quality notice",
["Vendor management notice: we regret to announce that the last two shipments from Supplier K",
"failed the quality-control check. Inspections found substandard materials",
"in three consecutive lots, which is unacceptable under our protocols.",
"We are implementing stricter measures: we will reject any lot that fails,",
"and repeated violations will result in the contract being terminated.",
"Orders have been cancelled and redirected to approved vendors.",
"Two incidents of this kind mean the supplier is immediately terminated.",
"Good supplier relationships depend on consistent quality."],
[M(0,"regret to announce","Regret to announce","遺憾地宣布"),M(1,"failed the quality-control check","Failed the quality-control check","未通過品質管制檢查"),M(1,"Inspections","Inspections","檢查"),M(1,"substandard materials","Substandard materials","不合格材料"),
M(2,"consecutive","Consecutive","連續的"),M(2,"unacceptable","Unacceptable","不可接受的"),M(2,"protocols","Protocols","規範、協定"),
M(3,"implementing","Implementing","實施"),M(3,"measures","Measures","措施"),M(3,"reject","Reject","拒絕"),
M(4,"repeated","Repeated","屢次的"),M(4,"violations","Violations","違反"),M(4,"terminated","Terminated","終止"),
M(5,"cancelled","Cancelled","取消"),M(5,"redirected","Redirected","重新導向、轉向"),
M(6,"incidents","Incidents","事件"),M(6,"immediately terminated","Immediately terminated","立即終止"),M(7,"supplier relationships","Supplier relationships","供應商關係"),M(0,"Vendor management","Vendor management","供應商管理")],
subtitle="To: Procurement team  ·  From: Head of Vendor Management")
# ===== 5-4 =====
make_doc("toeic-5-4-b","paper","MEETING AGENDA — Quarterly Strategy Session",
["Meeting agenda — Strategy session, Q2","09:00  Staff meeting opens · attendance check · department heads' briefing",
"09:30  Go over the figures — project timeline and stakeholder engagement",
"10:30  Conference call with regional offices (we may switch the sessions if needed)",
"11:00  Presentation skills workshop — please hold any questions until afterward",
"12:00  Action items & follow-up: Ms. Lin will take the meeting minutes,",
"       coordinate with team leaders and arrange for room bookings."],
[M(1,"Staff meeting","Staff meeting","員工會議"),M(1,"attendance","Attendance","出席"),M(1,"department heads","Department heads","部門主管"),M(1,"briefing","Briefing","簡報、說明"),
M(2,"Go over the figures","Go over the figures","檢視數據"),M(2,"project timeline","Project timeline","專案時程"),M(2,"stakeholder engagement","Stakeholder engagement","利害關係人參與"),
M(3,"Conference call","Conference call","電話會議"),M(3,"switch the sessions","Switch the sessions","調換議程順序"),
M(4,"Presentation skills","Presentation skills","簡報技巧"),M(4,"hold any questions","Hold any questions","保留問題"),M(4,"afterward","Afterward","之後"),
M(5,"Action items","Action items","行動項目"),M(5,"follow-up","Follow-up","後續追蹤"),M(5,"take the meeting minutes","Take the meeting minutes","記錄會議紀錄"),
M(6,"coordinate","Coordinate","協調"),M(6,"arrange for","Arrange for","安排"),M(0,"Meeting agenda","Meeting agenda","會議議程"),M(0,"Strategy session","Strategy session","策略會議")],
subtitle="Date: April 1  ·  Room 3B  ·  Meeting agenda distributed in advance")
make_doc("toeic-5-4-c","memo","To: All department heads",
["Subject: New format for quarterly reports — effective April 1",
"To keep you informed and improve team coordination, we will replace the",
"traditional format with an interactive approach that emphasizes visuals.",
"Guidelines will be distributed next week so you can familiarize your teams",
"with changes in advance; please allow two weeks of lead time and submit",
"reports by the 5th. Presenters will be rotating rather than permanently assigned;",
"this accommodates regional offices. Initial feedback is welcome — please inform HR."],
[M(0,"format","Format","格式"),M(0,"quarterly reports","Quarterly reports","季度報告"),M(0,"effective April 1","Effective April 1","自 4 月 1 日起生效"),
M(1,"keep you informed","Keep you informed","持續告知你"),M(1,"team coordination","Team coordination","團隊協調"),
M(2,"traditional format","Traditional format","傳統格式"),M(2,"interactive approach","Interactive approach","互動式方法"),M(2,"emphasizes","Emphasizes","強調"),
M(3,"Guidelines","Guidelines","準則"),M(3,"distributed","Distributed","發放"),M(3,"familiarize","Familiarize…with changes","使…熟悉變更"),
M(4,"in advance","In advance","事先、提前"),M(4,"lead time","Lead time","前置時間"),M(4,"submit","Submit","提交"),
M(5,"rotating","Rotating","輪流的"),M(5,"permanently assigned","Permanently assigned","固定指派的"),
M(6,"accommodates","Accommodates","配合、容納"),M(6,"regional offices","Regional offices","區域辦公室"),M(6,"Initial feedback","Initial feedback","初步回饋"),M(6,"inform","Inform","告知")],
subtitle="From: Operations Director  ·  Date: March 10")
make_doc("toeic-5-4-d","email","Mail — Pilot program: weekly updates",
["The revised protocol for the pilot program starts Monday.",
"Designated staff will distribute clearly marked forms; tasks are assigned to",
"each team leader. Preliminary data shows we reduced processing time by 25%.",
"Weekly updates and sharing of results at the Friday training session will",
"keep our methods consistent. Thank you for your cooperation —",
"this is a big step for organizational efficiency."],
[M(0,"revised","Revised","修訂"),M(0,"protocol","Protocol","規範、協定"),M(0,"pilot program","Pilot program","試辦計畫"),
M(1,"Designated staff","Designated staff","指定人員"),M(1,"distribute","Distribute","分發"),M(1,"clearly marked","Clearly marked","清楚標示的"),M(1,"assigned to","Assigned to","指派給"),
M(2,"Preliminary data","Preliminary data","初步數據"),M(2,"reduced processing time by 25%","Reduced…by 25%","減少 25%"),
M(3,"Weekly updates","Weekly updates","每週更新"),M(3,"sharing","Sharing","分享"),M(3,"training session","Training session","培訓課程"),
M(4,"consistent","Consistent","一致的"),M(4,"cooperation","Cooperation","合作"),M(5,"organizational efficiency","Organizational efficiency","組織效率")],
subtitle="From: project-office@company.com   To: pilot-team")
# ===== 5-5 =====
make_doc("toeic-5-5-b","news","PRESS RELEASE — Wesley Manufacturing named Top Manufacturer",
["We are proud to announce that Wesley Manufacturing has received the",
"Excellence in Manufacturing Award from Global Industry Review.",
"Our quality assurance program has been recognized internationally, and the",
"designation of \"top manufacturer\" reflects our dedication to the",
"highest-quality products. Every product meets or exceeds excellence standards;",
"this award-winning team has set new excellence standards for the industry.",
"The award has significantly strengthened our corporate reputation."],
[M(0,"We are proud to announce","We are proud to announce","我們很自豪地宣布"),M(0,"received","Received","獲得"),
M(1,"Excellence in Manufacturing Award","Excellence in Manufacturing Award","製造卓越獎"),M(1,"Global Industry Review","Global Industry Review","《全球產業評論》"),
M(2,"quality assurance","Quality assurance","品質保證"),M(2,"has been recognized internationally","Has been recognized internationally","已獲國際肯定"),
M(3,"designation","Designation","認證、稱號"),M(3,"top manufacturer","Top manufacturer","頂尖製造商"),M(3,"dedication","Dedication","投入、奉獻"),
M(4,"highest-quality products","Highest-quality products","最高品質的產品"),M(4,"meets","Meets","達到（標準）"),M(4,"excellence standards","Excellence standards","卓越標準"),
M(5,"award-winning","Award-winning","獲獎的"),M(5,"set new excellence standards","Set new excellence standards","樹立新的卓越標準"),
M(6,"significantly","Significantly","大幅地"),M(6,"strengthened","Strengthened","強化"),M(6,"corporate reputation","Corporate reputation","企業聲譽")],
subtitle="For immediate release · September 17")
make_doc("toeic-5-5-c","paper","CUSTOMER TESTIMONIALS — What our clients say",
["Customer testimonials collected this year:","\"Superior customer service and an enhanced product line,\" stated one client.",
"We showcase these testimonials to praise the team's outstanding contributions.",
"We are launching a recognition program and expanding it to all regions:",
"long-term employees will be honored with certificates at the anniversary celebration.",
"Our CSR initiatives — community engagement, sustainability initiatives and",
"waste reduction programs — cut our carbon footprint by 30%, showing our",
"commitment to environmental responsibility."],
[M(1,"Superior customer service","Superior customer service","優質客戶服務"),M(1,"enhanced","Enhanced","強化的"),M(1,"stated","Stated","表示"),
M(2,"showcase","Showcase","展示"),M(2,"testimonials","Testimonials","見證、推薦"),M(2,"praise","Praise","讚揚"),M(2,"outstanding contributions","Outstanding contributions","傑出貢獻"),
M(3,"launching","Launching","推出"),M(3,"recognition program","Recognition program","表彰計畫"),M(3,"expanding","Expanding","擴大"),
M(4,"long-term employees","Long-term employees","長期員工"),M(4,"honored","Honor","表揚"),M(4,"certificates","Certificates","證書"),
M(5,"CSR initiatives","CSR initiatives","企業社會責任計畫"),M(5,"community engagement","Community engagement","社區參與"),M(5,"sustainability initiatives","Sustainability initiatives","永續計畫"),
M(6,"waste reduction programs","Waste reduction programs","減廢計畫"),M(6,"carbon footprint","Carbon footprint","碳足跡"),M(7,"commitment","Commitment","承諾、投入"),M(7,"environmental responsibility","Environmental responsibility","環境責任"),M(0,"Customer testimonials","Customer testimonials","客戶推薦、客戶見證")],
subtitle="Annual report · page 12")
make_doc("toeic-5-5-d","paper","INVITATION — 20th Anniversary Celebration",
["We are delighted to invite you to our anniversary celebration on October 12.",
"In recognition of this milestone, we want to thank you for two decades",
"of accomplishment. A Certificate of Achievement will be presented",
"to each long-term employee, followed by a reception at 6 p.m.",
"Dress code: business attire.  RSVP by October 1 to events@wesley.com."],
[M(0,"We are delighted to invite","We are delighted to invite","我們很高興邀請"),M(0,"anniversary celebration","Anniversary celebration","週年慶祝"),
M(1,"In recognition of this milestone","In recognition of this milestone","為表彰此里程碑"),M(1,"we want to thank you","We want to thank you","我們要感謝各位"),
M(2,"accomplishment","Accomplishment","成就"),M(2,"Certificate of Achievement","Certificate of Achievement","成就證書"),
M(3,"reception","Reception","酒會、接待會"),M(4,"business attire","Business attire","商務正裝"),M(4,"RSVP","RSVP","回覆是否出席")],
subtitle="Wesley Manufacturing · Grand Ballroom, Hotel Royal")
