# -*- coding: utf-8 -*-
from docs import *
from photo import scene,fetch
import json
M=lambda i,ph,en,zh:(i,ph,en,zh,"l")
P=lambda k:fetch(json.load(open(f'p{k}A.json'))["url"])
# ---- photos ----
scene("toeic-6-1-a",P("61"),[(1000,120,"Shuttle service","接駁服務",(1000,300),28),(450,50,"Ground transportation","地面交通",None,22),
 (350,330,"Car rental","租車服務",(375,160),24),(600,900,"Pickup location","取車地點",(750,825),22),(1300,700,"Express service","快速服務",(1200,600),22),
 (1350,150,"Outside Terminal C","C 航廈外面",(1400,300),20),(1300,900,"Drop-off","還車／放人下車",(1250,800),22),(250,600,"Every 15 minutes","每 15 分鐘一班",None,20)],
 "Photo: 4300streetcar, Wikimedia Commons (CC BY 4.0)")
scene("toeic-6-2-a",P("62"),[(500,180,"Gate B12","B12 登機門",(500,325),28),(1175,280,"Itinerary","行程表、旅行路線",(1175,425),24),
 (300,900,"Customer service desk","客服櫃台",(375,750),22),(1400,930,"Receipts","收據",(1400,800),22),(850,760,"Mechanical issue","機械故障",(1175,440),20)],
 "Photo: HuangWending18072009, Wikimedia Commons (CC0)")
scene("toeic-6-3-a",P("63"),[(1175,180,"At Platform 1","在 1 號月台",(1175,80),24),(825,300,"Delayed by approximately three hours","延誤約三小時",(825,450),20),
 (1375,450,"Urgent track maintenance","緊急軌道維護",(1375,625),20),(300,300,"Service suspension","服務暫停／中斷",(400,450),22),
 (700,930,"Every 30 minutes","每 30 分鐘一班",(750,880),22),(1300,900,"Disruption","中斷、干擾",(1300,800),24)],
 "Photo: Smiley.toerist, Wikimedia Commons (CC BY-SA 4.0)")
scene("toeic-6-4-a",P("64"),[(800,120,"Hotel lobby","飯店大廳",None,30),(1200,330,"Checked into","辦理入住",(1200,480),24),
 (1450,700,"Late check-in","深夜入住",(1350,520),22),(300,250,"Accommodation","住宿、住處",(350,400),22),
 (1250,180,"Hotel lobby doubles as an art gallery","飯店大廳兼作藝廊",(1250,320),18),(700,900,"Complimentary breakfast","免費早餐",(700,700),22),
 (275,900,"Souvenir","紀念品",(275,650),22),(1450,900,"Room service","客房服務",(1450,780),22)],
 "Photo: Nicholas Hartmann, Wikimedia Commons (CC BY-SA 4.0)")
scene("toeic-6-5-a",P("65"),[(1100,120,"Departure board","出發航班看板",(1100,380),28),(300,120,"Flight status","航班狀態",(700,425),24),
 (900,930,"Gate C15","C15 登機門",(825,520),24),(450,930,"Final boarding call","最後登機廣播",(750,750),20),(1350,930,"Live route updates","即時航線更新",(1250,650),20),
 (200,250,"Shuttle train","機場捷運／接駁電車",(200,300),18)],
 "Photo: Tiia Monto, Wikimedia Commons (CC BY-SA 3.0)")
# ---- docs ----
make_doc("toeic-6-1-b","email","Mail — Car rental confirmation (reserved online)",
["Your car rental has been reserved online: midsize sedan, unlimited mileage.",
"Pickup location: Airport Rental Car Center (within walking distance of Terminal C).",
"Drop-off: downtown drop-off location, 5 p.m. — free transportation back to the terminal.",
"Frequent flyers: we have added 500 bonus points to your account.",
"Transportation vouchers for the shuttle are free for customers."],
[M(0,"car rental","Car rental","租車服務"),M(0,"reserved online","Reserved online","線上預訂"),M(0,"midsize sedan","Midsize sedan","中型轎車"),M(0,"unlimited mileage","Unlimited mileage","無限里程"),
M(1,"Pickup location","Pickup location","取車地點"),M(1,"within walking distance","Within walking distance","步行可達距離"),
M(2,"Drop-off","Drop-off","還車／放人下車"),M(2,"downtown drop-off location","Downtown drop-off location","市中心還車地點"),M(2,"free transportation","Free transportation","免費交通"),
M(3,"Frequent flyers","Frequent flyers","飛行常客"),M(3,"added 500 bonus points","Added 500 bonus points","增加 500 紅利點數"),
M(4,"Transportation vouchers","Transportation vouchers","交通折價券／乘車券"),M(4,"free for customers","Free for customers","顧客免費")],
subtitle="From: reservations@aircar.com")
make_doc("toeic-6-1-c","paper","AIRPORT SHUTTLE SERVICE — Ground Transportation Notice",
["Shuttle service departs every 15 minutes from outside Terminal C.",
"Bus cost: $3 (express service $6). Real-time traffic updates on our app.",
"Today: heavy traffic on the route — buses delayed by 25 minutes.",
"Customer feedback: \"The shuttle departure time wasn't posted, so we had a 20-minute wait.\"",
"Our reply: we have improved our shuttle signage and added a display at every stop."],
[M(0,"Shuttle service","Shuttle service","接駁服務"),M(0,"every 15 minutes","Every 15 minutes","每 15 分鐘一班"),M(0,"outside Terminal C","Outside Terminal C","C 航廈外面"),
M(1,"Bus cost","Bus cost","公車費用／票價"),M(1,"express service","Express service","快速服務"),M(1,"Real-time traffic updates","Real-time traffic updates","即時交通更新"),
M(2,"heavy traffic on the route","Heavy traffic on the route","路線交通擁堵"),M(2,"delayed by 25 minutes","Delayed by 25 minutes","延誤 25 分鐘"),
M(3,"shuttle departure time wasn't posted","Shuttle departure time wasn't posted","接駁車出發時間未張貼"),M(3,"20-minute wait","20-minute wait","等待 20 分鐘"),
M(4,"improved our shuttle signage","Improved our shuttle signage","改善接駁車標示")],
subtitle="Ground transportation desk · Terminal C arrivals level")
make_doc("toeic-6-2-b","email","Mail — Reservation confirmed (Corporate booking platform)",
["Thank you for choosing our corporate booking platform to make a reservation.",
"Booking: premium conference room for a corporate training session, entire day.",
"Corporate rate applied plus a group discount of 20 percent (more than 20 rooms).",
"Confirmation number: HX-77120 — confirmation numbers are instantly generated.",
"Cancellation policy: cancel 48 hours in advance without any penalties;",
"later cancellations are charged 50 percent of the total fare.",
"Our CFO notes that clients save an average of 35 percent with this platform.",
"— Maria Rodriguez, Travel Coordinator"],
[M(0,"corporate booking platform","Corporate booking platform","企業預訂平台"),M(0,"make a reservation","Make a reservation","進行預訂"),
M(1,"premium conference room","Premium conference room","高級會議室"),M(1,"corporate training session","Corporate training session","企業培訓課程"),M(1,"entire day","Entire day","整天"),
M(2,"Corporate rate","Corporate rate","企業優惠價"),M(2,"group discount of 20 percent","Group discount of 20 percent","20% 的團體折扣"),M(2,"more than 20 rooms","More than 20 rooms","超過 20 間房"),
M(3,"Confirmation number","Confirmation number","確認號碼"),M(3,"confirmation numbers are instantly generated","Confirmation numbers are instantly generated","確認號碼立即生成"),
M(4,"Cancellation policy","Cancellation policy","取消政策"),M(4,"48 hours in advance","48 hours in advance","提前 48 小時"),M(4,"without any penalties","Without any penalties","沒有任何罰金"),
M(5,"50 percent of the total fare","50 percent of the total fare","總費用的 50%"),M(6,"CFO","CFO","財務長"),M(6,"average of 35 percent","Average of 35 percent","平均 35%"),
M(7,"Maria Rodriguez, Travel Coordinator","Maria Rodriguez, Travel Coordinator","旅遊協調員瑪麗亞")],
subtitle="From: travel@company.com")
make_doc("toeic-6-2-c","paper","FLIGHT CHANGE NOTICE — Reservation change request",
["Reservation change request: due to a mechanical issue, flight TX 204 now departs from Gate B12 at 18:40.",
"A revised itinerary is attached. You may request a full refund of the fare difference",
"or a 30 percent discount voucher for a future trip (or a full refund of the ticket).",
"Keep all receipts for your expense reports.",
"Questions? Visit the customer service desk near Gate B10."],
[M(0,"mechanical issue","Mechanical issue","機械故障"),M(0,"Gate B12","Gate B12","B12 登機門"),
M(1,"revised itinerary","Revised itinerary","修改後的行程表"),M(1,"full refund of the fare difference","Full refund of the fare difference","差價全額退款"),
M(2,"30 percent discount voucher","30 percent discount voucher","30% 折扣券"),M(2,"full refund","Full refund","全額退款"),
M(3,"receipts","Receipts","收據"),M(3,"expense reports","Expense reports","費用報銷報告"),M(4,"customer service desk","Customer service desk","客服櫃台"),M(0,"Reservation change request","Reservation change request","預訂變更請求")],
subtitle="Reservation change request · TX Airlines")
make_doc("toeic-6-3-b","paper","SERVICE DISRUPTION NOTICE — Metro Line 2",
["Service suspension between Central and Harbor due to urgent track maintenance.",
"A technical issue and a mechanical problem were found; estimated time of",
"service restoration: 14:30. Replacement buses run every 30 minutes at Platform 1.",
"Passengers with connecting flights: trains are delayed by approximately three hours;",
"meal vouchers are available at the ticket office. We apologize for the disruption."],
[M(0,"Service suspension","Service suspension","服務暫停／中斷"),M(0,"urgent track maintenance","Urgent track maintenance","緊急軌道維護"),
M(1,"technical issue","Technical issue","技術問題"),M(1,"mechanical problem","Mechanical problem","機械故障"),M(1,"estimated time","Estimated time","預估時間"),
M(2,"service restoration","Service restoration","服務恢復"),M(2,"every 30 minutes","Every 30 minutes","每 30 分鐘一班"),M(2,"at Platform 1","At Platform 1","在 1 號月台"),
M(3,"connecting flights","Connecting flights","轉機／聯程航班"),M(3,"delayed by approximately three hours","Delayed by approximately three hours","延誤約三小時"),
M(4,"meal vouchers","Meal vouchers","餐飲券"),M(4,"disruption","Disruption","中斷、干擾")],
subtitle="Service disruption · Posted 09:15")
make_doc("toeic-6-3-c","email","Mail — Re: Formal complaint / compensation",
["I would like to file a complaint about yesterday's three-hour delay.",
"Reply: We have received your formal complaint. As compensation we will issue",
"a $50 travel voucher and waive the $15 assessment fee on your ticket change."],
[M(0,"file a complaint","File a complaint","提出申訴／客訴"),M(1,"formal complaint","Formal complaint","正式申訴"),M(1,"compensation","Compensation","補償、賠償"),
M(2,"travel voucher","Travel voucher","旅行折價券"),M(2,"waive","Waive","豁免、免除（費用）"),M(2,"assessment fee","Assessment fee","評估費／手續費")],
subtitle="From: customer.care@metro.com")
make_doc("toeic-6-4-b","email","Mail — Extend my reservation",
["I checked into the Grand Hotel yesterday (late check-in after 10 PM).",
"Because of an unexpected business meeting, I need to extend my reservation by two nights.",
"The accommodation is great: complimentary breakfast, room service, and the",
"hotel lobby doubles as an art gallery. The gift shop has nice souvenirs,",
"though the elevator is out of service. I plan some sightseeing with guided tours",
"tomorrow — the front desk staff seemed overwhelmed, so I am booking online."],
[M(0,"checked into","Checked into","辦理入住"),M(0,"late check-in after 10 PM","Late check-in after 10 PM","晚上 10 點後的深夜入住"),
M(1,"unexpected business meeting","Unexpected business meeting","突發的商務會議"),M(1,"extend my reservation","Extend my reservation","延長預訂／延住"),
M(2,"accommodation","Accommodation","住宿、住處"),M(2,"complimentary breakfast","Complimentary breakfast","免費早餐"),M(2,"room service","Room service","客房服務"),
M(3,"hotel lobby doubles as an art gallery","Hotel lobby doubles as an art gallery","飯店大廳兼作藝廊"),M(3,"gift shop","Gift shop","禮品店"),M(3,"souvenirs","Souvenir","紀念品"),
M(4,"out of service","Out of service","暫停服務／損壞"),M(4,"sightseeing","Sightseeing","觀光、遊覽"),M(4,"guided tours","Guided tours","有導覽的行程"),M(5,"overwhelmed","Overwhelmed","應接不暇")],
subtitle="From: elaine@company.com   To: reservations@grandhotel.com")
make_doc("toeic-6-5-b","paper","GATE C15 — Boarding information · Flight TX 204",
["Check the departure board for flight status; live route updates and SMS notifications available.",
"Final boarding call: passengers with a boarding pass are permitted to board 15 minutes before departure.",
"Luggage restrictions: one bag in the overhead compartment; extra bags incur a fee of $75.",
"Please review the safety procedures; turbulence is expected over the mountains.",
"Arrivals: the shuttle train to the baggage claim area leaves from the counter near Platform 3",
"(platform counter); checked bags arrive within 20 minutes."],
[M(0,"departure board","Departure board","出發航班看板"),M(0,"flight status","Flight status","航班狀態"),M(0,"live route updates","Live route updates","即時航線更新"),M(0,"SMS notifications","SMS notifications","簡訊通知"),
M(1,"Final boarding call","Final boarding call","最後登機廣播"),M(1,"boarding pass","Boarding pass","登機證"),M(1,"permitted to board","Permitted to board","允許登機"),M(1,"15 minutes before departure","15 minutes before departure","起飛前 15 分鐘"),
M(2,"Luggage restrictions","Luggage restrictions","行李限制"),M(2,"overhead compartment","Overhead compartment","頭頂上方置物箱"),M(2,"incur a fee of $75","Incur a fee of $75","產生 75 美元費用"),
M(3,"safety procedures","Safety procedures","安全程序"),M(3,"turbulence","Turbulence","亂流"),
M(4,"shuttle train","Shuttle train","機場捷運／接駁電車"),M(4,"baggage claim area","Baggage claim area","行李提領區"),M(4,"counter near Platform 3","Counter near Platform 3","3 號月台旁的櫃台"),
M(5,"platform counter","Platform counter","月台櫃台"),M(5,"arrive within 20 minutes","Arrive within 20 minutes","20 分鐘之內送達")],
subtitle="Gate C15 · Boarding 18:10 · Departure 18:40")
