# -*- coding: utf-8 -*-
from docs import *
from photo import scene,fetch
import json
M=lambda i,ph,en,zh:(i,ph,en,zh,"l")
P=lambda k:fetch(json.load(open(f'p{k}A.json'))["url"])
scene("toeic-7-1-a",P("71"),[(800,60,"Interview","面試",None,30),(1300,150,"HR department","人力資源部",(1150,300),24),(250,150,"Candidates","候選人、應徵者",(240,500),24),
 (620,900,"Résumé","履歷表",(900,760),26),(1400,930,"Cover letter","求職信、自薦信",(1300,860),22),(1400,700,"Qualifications","資格、資歷條件",(1150,600),22),(250,930,"Ideal candidate","理想的候選人",(240,750),22)],
 "Photo: Oregon DOT, Flickr (CC BY 2.0)")
scene("toeic-7-3-a",P("73"),[(800,70,"Training sessions","培訓課程",None,30),(1300,200,"Skills development program","技能發展課程",(1100,300),20),(300,150,"Data analytics","資料分析",(290,450),24),
 (1300,700,"Mentor","導師",(1000,500),26),(480,930,"Registration","報名",(480,620),24),(1200,900,"Workshop on effective communication","有效溝通工作坊",(1152,660),18),(250,930,"Supervisor","主管",(400,780),24)],
 "Photo: sridgway, Flickr (CC BY 2.0)")
scene("toeic-7-4-a",P("74"),[(800,70,"Lunch rush","午餐尖峰時段",None,30),(400,220,"Cover my shift","幫我代班",(400,450),24),(720,150,"Work some overtime","加班",(720,380),22),
 (1008,100,"Regular shift","正常班次",(1008,280),22),(1392,220,"Eight-hour shift","八小時班次",(1392,420),22),(1200,720,"Switch","交換（班次）",(1040,640),24),(1450,930,"Closing","打烊時間",(1400,800),24),(250,930,"Head out","離開、出發",(400,800),24)],
 "Photo: PattayaPatrol, Wikimedia Commons (CC BY-SA 4.0)")
# ---- 7-1 docs ----
make_doc("toeic-7-1-b","paper","JOB POSTING — Marketing Manager Position (Full-time)",
["Marketing manager position (full-time position): due to expansion, we are seeking a qualified professional to fill this vacancy.",
"The ideal candidate has extensive experience in client relations and digital marketing experience",
"(minimum 7 years), professional certifications, and a collaborative mindset.",
"Applicants should submit their application (CV or résumé, cover letter, references",
"with contact information) through the HR portal. Timeline for hiring: 4 weeks.",
"This is a permanent position; remote work is available two days a week.",
"We are an equal opportunity employer building a diverse workforce."],
[M(0,"due to expansion","Due to expansion","由於業務擴張"),M(0,"seeking","Seeking","尋找、招募"),M(0,"qualified professional","Qualified professional","合格的專業人士"),M(0,"fill this vacancy","Fill this vacancy","填補職缺"),
M(1,"ideal candidate","Ideal candidate","理想的候選人"),M(1,"extensive experience","Extensive experience","豐富的經驗"),M(1,"client relations","Client relations","客戶關係"),M(1,"digital marketing experience","Digital marketing experience","數位行銷經驗"),
M(2,"minimum 7 years","Minimum 7 years","至少 7 年"),M(2,"professional certifications","Professional certifications","專業證照"),M(2,"collaborative mindset","Collaborative mindset","協作心態"),
M(3,"Applicants","Applicants","申請者"),M(3,"submit their application","Submit their application","提交申請"),M(3,"CV","CV","履歷"),M(3,"references","References","推薦人"),
M(4,"contact information","Contact information","聯絡資訊"),M(4,"HR portal","HR portal","人資入口網站"),M(4,"Timeline for hiring","Timeline for hiring","招聘時程"),
M(5,"permanent","Permanent","永久的、正式的"),M(5,"remote work","Remote work","遠距工作"),M(6,"equal opportunity employer","Equal opportunity employer","平等機會雇主"),M(6,"workforce","Workforce","勞動力、全體員工"),M(0,"Marketing manager position","Marketing manager position","行銷經理職位"),M(0,"full-time position","Full-time position","全職職位")],
subtitle="Openings · Marketing manager position · Full-time position · Ref. MK-2026")
make_doc("toeic-7-1-c","email","Mail — Recruitment process & new employee orientation",
["Our recruitment process: application review → phone screening → panel interview.",
"Shortlisted candidates will be asked for professional references; we value work ethic.",
"Hiring decisions are made within two weeks of the final interview.",
"New employee orientation is on the first Monday; please complete the",
"onboarding documentation in the HR portal before then. There are three openings.",
"Welcome — your contributions will help us reach our next milestone.",
"The hiring process ends when the offer letter is signed."],
[M(0,"recruitment process","Recruitment process","招募流程"),M(0,"phone screening","Phone screening","電話初步篩選"),M(0,"panel interview","Panel interview","小組面試"),
M(1,"Shortlisted candidates","Shortlisted candidates","入圍候選人"),M(1,"professional references","Professional references","專業推薦人"),M(1,"work ethic","Work ethic","工作態度"),
M(2,"Hiring decisions","Hiring decisions","錄用決定"),M(3,"New employee orientation","New employee orientation","新進員工說明會"),
M(4,"onboarding documentation","Onboarding documentation","入職文件"),M(4,"openings","Openings","職缺"),M(5,"contributions","Contributions","貢獻"),M(5,"milestone","Milestone","里程碑"),M(6,"hiring process","Hiring process","招聘流程"),M(0,"application","Application","申請（書）")],
subtitle="From: hr@company.com   To: candidates")
# ---- 7-2 docs ----
make_doc("toeic-7-2-b","paper","OFFER LETTER — Compensation package",
["Your compensation package: a competitive salary commensurate with experience and expertise.",
"Base salary: $72,000; total compensation includes an annual bonus and generous benefits.",
"Compensation structure outlines market rates; a salary adjustment (12% raise) follows",
"a successful performance review after the probationary period.",
"Retirement plan: pension contributions plus a 401(k) matching program — the company",
"matches dollar-for-dollar up to 5%; vesting after three years. You are eligible",
"for retirement planning sessions (call HR, ext. 204)."],
[M(0,"competitive salary","Competitive salary","具市場競爭力的薪資"),M(0,"commensurate with experience","Commensurate with experience","與經驗相稱"),M(0,"expertise","Expertise","專業知識、專長"),
M(1,"Base salary","Base salary","底薪"),M(1,"total compensation","Total compensation","總薪酬"),M(1,"annual bonus","Annual bonus","年度獎金"),M(1,"generous benefits","Generous benefits","豐厚的福利"),
M(2,"Compensation structure","Compensation structure","薪酬結構"),M(2,"outlines","Outlines","概述"),M(2,"market rates","Market rates","市場行情"),M(2,"salary adjustment","Salary adjustment","薪資調整"),M(2,"12% raise","12% raise","加薪 12%"),
M(3,"performance review","Performance review","績效評估"),M(3,"probationary period","Probationary period","試用期"),
M(4,"Retirement plan","Retirement plan","退休計畫"),M(4,"pension contributions","Pension contributions","退休金提撥"),M(4,"401(k) matching program","401(k) matching program","401(k) 相對提撥計畫"),
M(5,"matches","Matches","相對提撥、比照"),M(5,"dollar-for-dollar","Dollar-for-dollar","一比一地"),M(5,"vesting","Vesting","（退休金）歸屬權"),M(5,"eligible","Eligible","符合資格的"),
M(6,"retirement planning sessions","Retirement planning sessions","退休規劃講座"),M(6,"ext.","Ext.","分機"),M(0,"compensation package","Compensation package","薪酬方案")],
subtitle="Compensation package for: Elaine Chi · Position: Marketing Manager")
make_doc("toeic-7-2-c","email","Mail — Benefits package update (effective January 1)",
["Our benefits package now includes enhanced health coverage (premiums fully paid),",
"a pension plan, a wellness program, 20 vacation days, and a sabbatical after 7 years.",
"Professional development courses are reimbursable through the streamlined",
"reimbursement program: submit claims with receipts within 10 business days;",
"documented expenses receive an approval code and are paid upon return.",
"The new policy is effective January 1; pension matching remains unchanged."],
[M(0,"benefits package","Benefits package","福利方案"),M(0,"enhanced health coverage","Enhanced health coverage","強化的健康保險"),M(0,"premiums","Premiums","保費"),
M(1,"pension plan","Pension plan","退休金計畫"),M(1,"wellness program","Wellness program","健康促進計畫"),M(1,"vacation days","Vacation days","休假天數"),M(1,"sabbatical","Sabbatical","帶薪長假、進修假"),
M(2,"Professional development","Professional development","專業進修"),M(2,"reimbursable","Reimbursable","可報銷的"),M(2,"streamlined","Streamlined","簡化的"),
M(3,"reimbursement program","Reimbursement program","報銷計畫"),M(3,"claims","Claims","（報銷）申請"),M(3,"receipts","Receipts","收據"),M(3,"business days","Business days","工作日"),
M(4,"documented","Documented","有憑證的"),M(4,"approval code","Approval code","核准代碼"),M(4,"upon return","Upon return","一返回即…"),
M(5,"effective","Effective","生效的"),M(5,"pension","Pension","退休金")],
subtitle="From: benefits@company.com   To: all-staff")
make_doc("toeic-7-2-d","slide","Performance Recognition Program — Incentives 2026",
["Incentive programs: quarterly incentives for teams meeting expectations,",
"a special bonus for exceptional performers, and an automatic raise for",
"every outstanding contributor whose innovative approach grows revenue.",
"The prestigious Employee of the Year award goes to the top performer.",
"Requests for reimbursement for award travel are accepted upon return."],
[M(0,"Incentive programs","Incentive programs","獎勵計畫"),M(0,"quarterly incentives","Quarterly incentives","季度獎勵"),M(0,"meeting expectations","Meeting expectations","達到預期"),
M(1,"special bonus","Special bonus","特別獎金"),M(1,"exceptional performers","Exceptional performers","表現卓越者"),M(1,"automatic raise","Automatic raise","自動加薪"),
M(2,"outstanding contributor","Outstanding contributor","傑出貢獻者"),M(2,"innovative approach","Innovative approach","創新做法"),M(2,"revenue","Revenue","營收"),
M(3,"prestigious","Prestigious","極具聲望的"),M(3,"Employee of the Year award","Employee of the Year award","年度最佳員工獎"),
M(4,"Requests for reimbursement","Requests for reimbursement","報銷申請"),M(0,"Incentive","Incentives","獎勵、誘因")],
subtitle="Performance recognition program · HR town hall · Slide 4")
# ---- 7-3 docs ----
make_doc("toeic-7-3-b","email","Mail — Annual performance review: self-assessment due",
["Your annual performance review is scheduled for May 3 with your supervisor.",
"The self-assessment and quarterly report are due by the deadline (April 25).",
"Highlight your achievements — this affects opportunities for promotion to senior roles.",
"Advancement opportunities and year-end bonuses depend on eligibility under the",
"performance management system; failure to do so may delay your review.",
"Effective immediately, continuous feedback replaces the old framework: monthly",
"check-ins with your mentor are mandatory to raise employee engagement."],
[M(0,"annual performance review","Annual performance review","年度績效評估"),M(0,"supervisor","Supervisor","主管"),
M(1,"self-assessment","Self-assessment","自我評估"),M(1,"quarterly report","Quarterly report","季度報告"),M(1,"due","Due","到期的、應繳交的"),M(1,"deadline","Deadline","截止日期"),
M(2,"Highlight your achievements","Highlight your achievements","凸顯你的成就"),M(2,"opportunities for promotion","Opportunities for promotion","晉升機會"),M(2,"senior roles","Senior roles","高階職位"),
M(3,"Advancement opportunities","Advancement opportunities","晉升機會"),M(3,"year-end bonuses","Year-end bonuses","年終獎金"),M(3,"eligibility","Eligibility","資格"),
M(4,"performance management system","Performance management system","績效管理系統"),M(4,"failure to do so","Failure to do so","未能如此做"),
M(5,"Effective immediately","Effective immediately","即刻生效"),M(5,"continuous feedback","Continuous feedback","持續回饋"),M(5,"framework","Framework","架構、框架"),
M(6,"check-ins","Check-ins","定期會談"),M(6,"mentor","Mentor","導師"),M(6,"mandatory","Mandatory","強制性的"),M(6,"employee engagement","Employee engagement","員工投入度")],
subtitle="From: hr@company.com")
make_doc("toeic-7-3-c","paper","SKILLS DEVELOPMENT PROGRAM — Registration open",
["Skills development: the professional development department is launching a pilot program:",
"training sessions in data analytics and a workshop on effective communication.",
"Space is limited — registration closes Friday; your manager must approve.",
"Qualified staff receive a certificate of completion; an initial assessment",
"and assessment tools are in the comprehensive guide. Time slots accommodate",
"all shifts. The mentorship program requires a six-month commitment."],
[M(0,"professional development department","Professional development department","專業發展部門"),M(0,"pilot program","Pilot program","試辦計畫"),
M(1,"training sessions","Training sessions","培訓課程"),M(1,"data analytics","Data analytics","資料分析"),M(1,"workshop on effective communication","Workshop on effective communication","有效溝通工作坊"),
M(2,"Space is limited","Space is limited","名額有限"),M(2,"registration","Registration","報名"),M(2,"approve","Approve","核准"),
M(3,"Qualified","Qualified","有資格的"),M(3,"certificate of completion","Certificate of completion","結業證書"),M(3,"initial assessment","Initial assessment","初步評估"),
M(4,"assessment tools","Assessment tools","評估工具"),M(4,"comprehensive guide","Comprehensive guide","完整指南"),M(4,"Time slots","Time slots","時段"),M(4,"accommodate","Accommodate","配合、容納"),
M(5,"mentorship program","Mentorship program","導師計畫"),M(5,"commitment","Commitment","承諾、投入"),M(0,"Skills development","Skills development","技能發展")],
subtitle="Skills development program · Spring term")
# ---- 7-4 docs ----
make_doc("toeic-7-4-b","paper","STAFF NOTICE — Vacation policy update & schedule changes",
["Vacation policy update: requests for time off must be submitted 14 days in advance",
"(two weeks' notice); any planned absence needs proper notice — we are strict",
"during peak seasons but flexible in emergencies. Advise a manager if you leave early.",
"Schedule changes: to cover a shift or switch, find an opening on the board.",
"Attendance issues: HR will handle your attendance records and paperwork.",
"Submit your hours by the deadline for payroll processing."],
[M(0,"policy update","Policy update","政策更新"),M(0,"time off","Time off","休假、請假"),M(0,"14 days in advance","14 days in advance","提前 14 天"),
M(1,"two weeks' notice","Two weeks' notice","兩週前預告"),M(1,"planned absence","Planned absence","預定缺勤"),M(1,"proper notice","Proper notice","適當的預告"),M(1,"strict","Strict","嚴格的"),
M(2,"peak seasons","Peak seasons","旺季"),M(2,"flexible","Flexible","有彈性的"),M(2,"emergencies","Emergencies","緊急情況"),M(2,"Advise a manager","Advise a manager","通知主管"),M(2,"leave early","Leave early","提早下班"),
M(3,"Schedule changes","Schedule changes","排班變更"),M(3,"cover a shift","Cover a shift","代班"),M(3,"opening","Opening","空檔、空缺"),
M(4,"Attendance issues","Attendance issues","出勤問題"),M(4,"handle your attendance records","Handle your attendance records","處理你的出勤紀錄"),M(4,"paperwork","Paperwork","文書作業"),
M(5,"Submit your hours","Submit their hours","提交工時"),M(5,"deadline","Deadline","截止日期"),M(5,"payroll processing","Payroll processing","薪資處理"),M(0,"Vacation policy","Vacation policy","休假政策")],
subtitle="Vacation policy · requesting time off · effective next month")
make_doc("toeic-7-4-c","email","Mail — Overtime compensation & this week's shifts",
["Overtime pay: work hours beyond a regular eight-hour shift are paid at the 1.5x rate",
"(time-and-a-half pay). Overtime compensation appears on the next payroll.",
"Two shifts are still outstanding — who is available for closing on Friday?",
"If there is an emergency, text me; I need to head out at 5 for my vacation.",
"Thanks for covering — I owe you one!  Attendance record must be approved by Sunday."],
[M(0,"Overtime pay","Overtime pay","加班費"),M(0,"work hours","Work hours","工時"),M(0,"regular eight-hour shift","Eight-hour shift","八小時班次"),M(0,"1.5x rate","1.5x rate","1.5 倍費率"),
M(1,"time-and-a-half pay","Time-and-a-half pay","1.5 倍薪資"),M(1,"Overtime compensation","Overtime compensation","加班補償"),M(1,"payroll","Payroll","薪資（作業）"),
M(2,"outstanding","Outstanding","尚未處理的"),M(2,"available","Available","有空的"),M(2,"closing","Closing","打烊時間"),
M(3,"emergency","Emergency","緊急狀況"),M(3,"head out","Head out","離開、出發"),M(3,"vacation","Vacation","休假"),
M(4,"I owe you one","I owe you one","我欠你一次人情"),M(4,"Attendance record","Attendance record","出勤紀錄"),M(4,"approved","Approve","核准"),M(0,"Overtime","Work some overtime","加班")],
subtitle="From: shift-manager@cafe.com   To: floor staff")
# ---- 7-5 docs ----
make_doc("toeic-7-5-b","email","Mail — Company picnic moved & employee appreciation dinner",
["The company picnic has been moved to Riverside Park instead of the original location.",
"Please attend — team-building activities will boost morale and build trust.",
"Our employee appreciation dinner is on May 20: a milestone celebration with",
"recognition for staff embodying company values. Keep up the excellent work!",
"Thank you for your dedication and outstanding performance this quarter."],
[M(0,"company picnic","Company picnic","公司野餐"),M(0,"moved to","Moved to","改期至"),M(0,"instead of","Instead of","而非"),M(0,"original location","Original location","原定地點"),
M(1,"attend","Attend","出席"),M(1,"team-building activities","Team-building activities","團隊建設活動"),M(1,"boost morale","Boost morale","提振士氣"),M(1,"build trust","Build trust","建立信任"),
M(2,"employee appreciation dinner","Employee appreciation dinner","員工感謝晚宴"),M(2,"milestone celebration","Milestone celebration","里程碑慶祝"),
M(3,"recognition","Recognition","肯定、表彰"),M(3,"embodying","Embodying","體現"),M(3,"company values","Company values","公司價值觀"),M(3,"Keep up the excellent work","Keep up the excellent work","繼續保持優異表現"),
M(4,"dedication","Dedication","奉獻、投入"),M(4,"outstanding performance","Outstanding performance","傑出表現")],
subtitle="From: people-team@company.com")
make_doc("toeic-7-5-c","slide","Workplace Culture — Employee Engagement Survey Results",
["Employee satisfaction survey: engagement scores rose 18% after our comprehensive initiative.",
"Organizational culture is an investment; our people are our greatest asset.",
"Employee morale, productivity and project completions all improved through",
"cross-departmental collaboration and team-building workshops we host monthly.",
"Flexible work arrangements, wellness programs and a mentorship system",
"are what sets us apart in a competitive industry."],
[M(0,"Employee satisfaction survey","Employee satisfaction survey","員工滿意度調查"),M(0,"engagement scores","Engagement scores","投入度分數"),M(0,"comprehensive initiative","Comprehensive initiative","全面性計畫"),
M(1,"Organizational culture","Organizational culture","組織文化"),M(1,"investment","Investment","投資"),M(1,"asset","Asset","資產"),
M(2,"Employee morale","Employee morale","員工士氣"),M(2,"productivity","Productivity","生產力"),M(2,"project completions","Project completions","專案完成"),
M(3,"cross-departmental collaboration","Cross-departmental collaboration","跨部門合作"),M(3,"team-building workshops","Team-building workshops","團隊建設工作坊"),M(3,"host","Host","舉辦、主辦"),
M(4,"Flexible work arrangements","Flexible work arrangements","彈性工作安排"),M(4,"wellness programs","Wellness programs","健康計畫"),M(4,"mentorship system","Mentorship system","導師制度"),
M(5,"sets us apart","Sets us apart","使我們與眾不同"),M(5,"competitive industry","Competitive industry","競爭激烈的產業"),M(0,"Employee","Employee engagement survey","員工投入度調查"),M(0,"survey","Workplace culture","職場文化")],
subtitle="Workplace culture · Employee engagement survey 2026")
