# -*- coding: utf-8 -*-
from docs import *
from photo import scene,fetch
import json
M=lambda i,ph,en,zh:(i,ph,en,zh,"l")
P=lambda k:fetch(json.load(open(f'p{k}A.json'))["url"])
scene("toeic-8-2-a",P("82"),[(800,70,"Board meeting","董事會會議",None,30),(460,130,"All department heads must attend","所有部門主管必須出席",(460,420),18),(1240,130,"Interdepartmental meeting","跨部門會議",(1240,400),20),
 (500,900,"Take minutes","記錄會議紀錄",(500,640),24),(1100,900,"Agenda","會議議程",(1000,700),26),(1450,600,"Fifth floor","五樓",None,22),(800,930,"Collaboration project","合作專案",(800,760),20)],
 "Photo: OSCE PA, Flickr (CC BY-SA 2.0)")
scene("toeic-8-3-a",P("83"),[(500,120,"Make copies","影印、複印",(500,300),26),(1100,120,"Photocopier is jammed","影印機卡紙",(900,500),22),(1000,930,"Use the scanner and email","改用掃描與電子郵件",(1000,800),20),
 (200,500,"Equipment maintenance","設備維護",(250,650),20),(1350,330,"Second floor near the filing cabinet","二樓檔案櫃旁",None,17),(250,880,"Equipment failures","設備故障",(400,860),20)],
 "Photo: Alan Cleaver, Flickr (CC BY 2.0)")
scene("toeic-8-4-a",P("84"),[(980,880,"Sign in","簽到、登記姓名",(980,720),26),(300,300,"Security desk first","先去安全櫃台",(300,560),22),(820,200,"Visitor pass","訪客證",(820,360),24),
 (1300,900,"Notify reception in advance","提前通知前台",(1100,650),20),(740,300,"Drop the package at reception","將包裹留在前台",(740,470),18),(1400,250,"Extension 100","分機 100",(1280,480),22)],
 "Photo: Kristin Dos Santos, Flickr (CC BY-SA 2.0)")
scene("toeic-8-5-a",P("85"),[(800,70,"Office relocation","辦公室搬遷",None,30),(300,300,"Professional movers","專業搬家公司",(350,600),22),(1200,300,"Label personal items by August 15","8 月 15 日前為私人物品貼標籤",(1200,480),17),
 (700,260,"New premises","新址、新辦公大樓",(900,230),22),(300,900,"Minimize disruption","將混亂降至最低",(500,800),22),(1350,900,"Contingency plans","應變計劃",(1440,500),22)],
 "Photo: MoveON moving, Wikimedia Commons (CC BY-SA 4.0)")
# 8-1
make_doc("toeic-8-1-b","memo","New filing system · effective April 1",
["We are implementing a new filing system (cloud system) on April 1.",
"Client correspondence and external correspondence go to the third floor archive;",
"internal project documents and deliverables are organized by timeline.",
"Correspondence must be submitted digitally — no more paper forms;",
"digital submissions get a tracking number and a notification within the hour.",
"Training sessions on system features start next month; the new timeline",
"should address delays: processing time reduced by 40%."],
[M(0,"implementing","Implementing","實施、執行"),M(0,"new filing system","New filing system","新檔案歸檔系統"),M(0,"cloud system","Cloud system","雲端系統"),M(0,"April 1","April 1","4 月 1 日"),
M(1,"Client correspondence","Client correspondence","客戶往來信件"),M(1,"external correspondence","External correspondence","對外往來信件"),M(1,"third floor","Third floor","三樓"),
M(2,"internal project documents","Internal project documents","內部專案文件"),M(2,"deliverables","Deliverables","交付成果"),M(2,"organized by timeline","Organized by timeline","按時間軸整理"),
M(3,"Correspondence","Correspondence","往來信件"),M(3,"submitted digitally","Submitted digitally","數位化提交"),M(3,"paper forms","Paper forms","紙本表格"),
M(4,"digital submissions","Digital submissions","數位提交件"),M(4,"tracking number","Tracking number","追蹤號碼"),M(4,"notification","Notification","通知"),M(4,"within the hour","Within the hour","一小時之內"),
M(5,"Training sessions","Training sessions","培訓課程"),M(5,"system features","System features","系統功能"),M(5,"next month","Next month","下個月"),M(5,"new timeline","New timeline","新時程"),
M(6,"address delays","Address delays","解決延誤問題"),M(6,"processing time reduced","Processing time reduced","處理時間縮短")],
subtitle="To: all staff  ·  From: Administration")
make_doc("toeic-8-1-c","email","Mail — Expense report approved",
["Your expense report was approved and processed yesterday.",
"Reimbursement takes 5-7 business days; the online system shows the status.",
"Reminder: attach original invoices and receipts; the project deadline for",
"paperwork is Friday. New rule: 3-5 business days for approval,",
"then 5-7 business days for reimbursement."],
[M(0,"expense report","Expense report","費用報銷報告"),M(0,"approved","Approved","被核准"),M(0,"processed yesterday","Processed yesterday","昨天已處理完成"),
M(1,"Reimbursement","Reimbursement","報銷、退款"),M(1,"5-7 business days","5-7 business days","5 至 7 個工作日"),M(1,"online system","Online system","線上系統"),
M(2,"original invoices","Original invoices","原始發票"),M(2,"receipts","Receipts","收據"),M(2,"project deadline","Project deadline","專案截止日期"),
M(3,"paperwork","Paperwork","文書工作"),M(3,"3-5 business days for approval","3-5 business days for approval","3-5 個工作日審批"),M(4,"5-7 business days for reimbursement","5-7 business days for reimbursement","5-7 個工作日退款")],
subtitle="From: finance@company.com")
# 8-2
make_doc("toeic-8-2-b","email","Mail — Book a conference room / internal memo",
["I tried to book a conference room for the interdepartmental meeting, but it's taken.",
"Conference Room A on the second floor is free at 9 AM sharp; the board meeting",
"about the upcoming merger is on the fifth floor. To avoid scheduling conflicts,",
"send an internal memo — draft it now — and attach the agenda for review beforehand.",
"Please take detailed minutes; financial projections: see Janet in accounting.",
"Coordination of the collaboration project needs collaboration strategies by May 1."],
[M(0,"book a conference room","Book a conference room","預訂會議室"),M(0,"interdepartmental meeting","Interdepartmental meeting","跨部門會議"),M(0,"it's taken","It's taken","已被佔用"),
M(1,"Conference Room A on the second floor","Conference Room A on the second floor","二樓 A 會議室"),M(1,"9 AM sharp","At 9 AM sharp","上午 9 點整準時"),M(1,"board meeting","Board meeting","董事會會議"),
M(2,"upcoming merger","Upcoming merger","即將進行的合併案"),M(2,"fifth floor","Fifth floor","五樓"),M(2,"scheduling conflicts","Scheduling conflicts","日程衝突"),
M(3,"send an internal memo","Send an internal memo","發送內部備忘錄"),M(3,"draft it now","Draft it now","現在起草"),M(3,"agenda","Agenda","會議議程"),M(3,"review beforehand","Review beforehand","事先審閱"),
M(4,"take detailed minutes","Take detailed minutes","記錄詳細的會議紀錄"),M(4,"financial projections","Financial projections","財務預測"),M(4,"see Janet in accounting","See Janet in accounting","前往會計部找珍妮特"),
M(5,"Coordination","Coordination","協調"),M(5,"collaboration strategies","Collaboration strategies","協作策略"),M(5,"May 1","May 1","5 月 1 日")],
subtitle="From: project-lead@company.com")
make_doc("toeic-8-2-c","paper","CIRCULAR — Standardizing interdepartmental collaboration",
["Bulletin from the administrative team: room bookings must be made 48 hours in advance",
"(one week ahead for the boardroom). Standardizing our process improves",
"interdepartmental collaboration. Post every internal memo on the shared drive",
"within 24 hours and take minutes at every meeting."],
[M(0,"Bulletin","Bulletin","公告"),M(0,"administrative team","Administrative team","行政團隊"),M(0,"48 hours in advance","48 hours in advance","提前 48 小時"),
M(1,"one week ahead","One week ahead","提前一週"),M(1,"Standardizing","Standardizing","標準化"),M(2,"interdepartmental collaboration","Interdepartmental collaboration","跨部門協作"),M(2,"internal memo","Internal memo","內部備忘錄"),M(2,"shared drive","Shared drive","共享雲端硬碟"),
M(3,"within 24 hours","Within 24 hours","24 小時之內"),M(3,"take minutes","Take minutes","記錄會議紀錄"),M(0,"Bulletin from","Circular","通報、傳閱公告")],
subtitle="Circular No. 12 · Administrative team")
# 8-3
make_doc("toeic-8-3-b","email","Mail — Facilities: equipment maintenance & IT support",
["The photocopier is jammed again; to make copies, use the scanner and email for now.",
"For network problems, contact IT support immediately or submit a ticket through the online system —",
"this will prevent connectivity issues at all workstations.",
"Facilities department update: air-conditioning installation in the new wing takes",
"approximately three days (temperature fluctuations expected); air-conditioning repair completed on floor 2.",
"New filing cabinets for the storage room arrive by Friday — see reception to sign.",
"Our comprehensive maintenance program (monthly maintenance requests) will reduce",
"equipment failures and extend its lifespan. Some workstations are unavailable until then."],
[M(0,"photocopier is jammed","Photocopier is jammed","影印機卡紙"),M(0,"make copies","Make copies","影印"),M(0,"use the scanner and email","Use the scanner and email","改用掃描與電子郵件"),
M(1,"network problems","Network problems","網路問題"),M(1,"contact IT support immediately","Contact IT support immediately","立即聯絡 IT 支援"),M(1,"submit a ticket through the online system","Submit a ticket through the online system","透過線上系統提交工單"),
M(2,"prevent connectivity issues","Prevent connectivity issues","預防連線問題"),M(2,"workstations","Workstations","工作站"),
M(3,"Facilities department","Facilities department","設施管理部門"),M(3,"air-conditioning installation","Air-conditioning installation","冷氣安裝"),M(3,"new wing","New wing","新側翼大樓"),
M(4,"approximately three days","Approximately three days","大約三天"),M(4,"temperature fluctuations","Temperature fluctuations","溫度波動"),M(4,"air-conditioning repair completed","Air-conditioning repair completed","冷氣維修已完成"),
M(5,"filing cabinets","Filing cabinets","檔案櫃"),M(5,"storage room","Storage room","儲藏室"),M(5,"arrive by Friday","Arrive by Friday","週五前送達"),M(5,"see reception to sign","See reception to sign","前往前台簽名領取"),
M(6,"comprehensive maintenance program","Comprehensive maintenance program","全面的維護計畫"),M(6,"monthly maintenance requests","Monthly maintenance requests","每月維護申請"),
M(7,"equipment failures","Equipment failures","設備故障"),M(7,"extend its lifespan","Extend its lifespan","延長其使用壽命"),M(7,"unavailable","Unavailable","無法使用的"),M(1,"IT support","IT support","IT 支援")],
subtitle="From: facilities@company.com")
# 8-4
make_doc("toeic-8-4-b","paper","NEW SECURITY PROTOCOL — mandatory for everyone",
["New security protocol (mandatory for everyone):","Visitors: sign in at the security desk first to get a visitor pass; the host is responsible for",
"escorting them at all times. We no longer allow entry without a host — notify reception in advance.",
"Staff: your ID badge must be visible at all times (above the waist and facing forward);",
"return temporary access cards to the security desk when you leave — valid only for the date issued.",
"Replacement badges are issued within 24 hours. Enhanced security measures start Monday.",
"Deliveries: our courier service provider changed — the new courier partner comes twice daily,",
"at noon and 4 PM; delivery personnel should drop the package at reception. Mail room pickups",
"at 11 AM and 3 PM daily; before noon ➔ distributed by 2 PM. Personal packages prohibited.",
"The security guard will direct the courier properly. Questions: extension 100."],
[M(1,"sign in","Sign in","簽到"),M(1,"security desk first","Security desk first","先去安全櫃台"),M(1,"visitor pass","Visitor pass","訪客證"),
M(2,"escorting them at all times","Escorting them at all times","全程陪同"),M(2,"no longer allow entry","No longer allow entry","不再允許進入"),M(2,"notify reception in advance","Notify reception in advance","提前通知前台"),
M(3,"ID badge","ID badge","員工識別證"),M(3,"visible at all times","Visible at all times","始終保持可見"),M(3,"above the waist and facing forward","Above the waist and facing forward","腰部以上且朝前"),
M(4,"temporary access cards","Temporary access cards","臨時門禁卡"),M(4,"security desk when you leave","Return to the security desk when you leave","離開時歸還至保全處"),M(4,"valid only for the date issued","Valid only for the date issued","僅簽發當天有效"),
M(5,"Replacement badges","Replacement badges","替代用識別證"),M(5,"within 24 hours","Within 24 hours","24 小時之內"),M(5,"Enhanced security measures","Enhanced security measures","增強的安全措施"),
M(6,"courier service provider changed","Courier service provider changed","更換快遞服務商"),M(6,"new courier partner","New courier partner","新快遞合作夥伴"),M(6,"twice daily","Comes twice daily","每日收件兩次"),
M(7,"at noon and 4 PM","At noon and 4 PM","中午及下午 4 點"),M(7,"delivery personnel","Delivery personnel","送貨人員"),M(7,"drop the package at reception","Drop the package at reception","將包裹留在前台"),M(7,"Mail room","Mail room","收發室"),
M(8,"at 11 AM and 3 PM daily","Pickups at 11 AM and 3 PM daily","每日 11 點及 3 點取件"),M(8,"before noon ➔ distributed by 2 PM","Before noon ➔ distributed by 2 PM","中午前到貨下午 2 點前發放"),M(8,"Personal packages prohibited","Personal packages prohibited","禁止寄送個人私件"),
M(9,"security guard","Security guard","保全人員"),M(9,"direct the courier properly","Direct the courier properly","妥善引導快遞人員"),M(9,"extension 100","Extension 100","分機 100"),M(0,"New security protocol","New security protocol","新安全協定"),M(0,"mandatory for everyone","Mandatory for everyone","對每個人都是強制性的")],
subtitle="New security protocol · Express Delivery & visitor management · mandatory for everyone")
# 8-5
make_doc("toeic-8-5-b","email","Mail — Office relocation & system upgrade this weekend",
["Office relocation to our new premises at 450 Harbor Street is confirmed for August 20.",
"Professional movers will handle everything; label personal items by August 15 to minimize disruption.",
"The west wing elevator is out of service until Wednesday (temporary malfunction) — the new building",
"has three elevators plus a service elevator. Expect a temporary office closure on Friday afternoon.",
"System upgrade this weekend: back up files before Thursday evening; data migration starts Friday.",
"System implementation is a gradual rollout / transitioning separately by department (September 1).",
"Training on Thursday — training is mandatory; Tuesday's session at 3 PM in Conference Room B covers",
"contingency plans; contingency planning and the help desk (ext. 300) support the rollout."],
[M(0,"Office relocation","Office relocation","辦公室搬遷"),M(0,"new premises","New premises","新址"),M(0,"450 Harbor Street","450 Harbor Street","港口街 450 號"),M(0,"confirmed for August 20","Confirmed for August 20","確認於 8 月 20 日"),
M(1,"Professional movers","Professional movers","專業搬家公司"),M(1,"label personal items by August 15","Label personal items by August 15","8 月 15 日前貼標籤"),M(1,"minimize disruption","Minimize disruption","將中斷降至最低"),
M(2,"west wing elevator is out of service until Wednesday","West wing elevator out of service until Wednesday","西翼電梯停用至週三"),M(2,"temporary malfunction","Temporary malfunction","暫時性故障"),
M(3,"three elevators plus a service elevator","Three elevators plus a service elevator","3 部客梯加 1 部貨梯"),M(3,"temporary office closure on Friday afternoon","Temporary office closure on Friday afternoon","週五下午暫時關閉"),
M(4,"System upgrade this weekend","System upgrade this weekend","本週末系統升級"),M(4,"back up files before Thursday evening","Back up files before Thursday evening","週四晚間前備份"),M(4,"data migration","Data migration","資料轉移"),
M(5,"System implementation","System implementation","系統導入"),M(5,"gradual rollout / transitioning separately","Gradual rollout / transitioning separately","漸進式推出、分開過渡"),M(5,"September 1","September 1","9 月 1 日"),
M(6,"Training on Thursday","Training on Thursday","週四培訓"),M(6,"training is mandatory","Training is mandatory","培訓是強制的"),M(6,"Tuesday's session at 3 PM in Conference Room B","Tuesday's session at 3 PM in Conference Room B","週二下午 3 點 B 會議室"),
M(7,"contingency plans","Contingency plans","應變計劃"),M(7,"contingency planning","Contingency planning","應變規劃"),M(7,"help desk","Help desk","IT 服務台"),M(7,"rollout","Rollout","推出、導入"),M(1,"disruption","Disruption","中斷、混亂"),M(2,"out of service","Elevator out of service","電梯停用")],
subtitle="From: operations@company.com   To: all-staff")
